### ISSUE TITLE
Crash involving iris while doing nothing in particular

### ISSUE THREAD

**Issue by truepurpledino** [TeamAOF/All-of-Fabric-6#1]
Seems to involve Iris. I was using Complementary Shaders 4.6, with some ressource packs and the game seemed to perform well up until the crash. https://aofpaste.com/hagopozezu.yaml

Extra mods I've added :
- Rebind Narrator
- Smooth Swapping
- Very many players
- Chat Heads
- Falling leaves
- Krypton
- Forget me chunk
- Sodium Extra
- Zoomify

Ressource packs used :
- AOF emissive textures
- Better Leaves
- Classic Emissive Ores
- Crops 3D
- Dramatic skys
- Roman Numerals
- Vanilla tweaks

**Comment by Clonephaze** [comment]
This probably is this same issue I've been running into, I reported the issue on their github tracker and was told it was a known issue. https://github.com/IrisShaders/Iris/issues/1724
