### ISSUE TITLE
All items requiring a copper sheet from create are missing recipes

### ISSUE THREAD

**Issue by Clonephaze** [TeamAOF/All-of-Fabric-6#10]
It seems like the unification of "plates" replaced copper sheets from create with copper plates from modern industrialization, but create recipes require specifically "copper sheets" so all of the items needing them are missing recipes. "Fluid Tank, Fluid Pipe, Hose Pulley, Copper Valve Handle, Display Link". However, getting the copper sheets from creative mode and attempting to craft with the normal recipes will still craft the item.

**Comment by Clonephaze** [comment]
![Fluid Tank can craft](https://user-images.githubusercontent.com/6809805/203122197-cf9360df-768e-4e12-af87-2ecb35ec6eaf.png)
![Fluid tank no recipe](https://user-images.githubusercontent.com/6809805/203122203-e02442e3-48db-4dd7-9776-3e4a17251e9d.png)

**Comment by ImAK9** [comment]
Will be fixed in next update
