### ISSUE TITLE
[Bug] Gamer Axe (Tooltip)

### ISSUE THREAD

**Issue by birdzhan99** [TeamAOF/All-of-Fabric-6#101]
When you look to the gamer axe tooltip the game crash .

Error message : 

The game crashed whilst rendering screen
Error: java.lang.IllegalArgumentException: Unknown TooltipComponent

**Comment by hokomili** [comment]
Same happens to steam mining drill.

**Comment by Linguardium** [comment]
its a problem with TieredZ

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/aca317b23ed720b48a4cfbff76cc81398934b097](https://github.com/Globox1997/tiered/commit/aca317b23ed720b48a4cfbff76cc81398934b097)
