### ISSUE TITLE
Trying to open quest book but doesn't work and Crash on client side opening the FTB chunks Tab

### ISSUE THREAD

**Issue by himhimbb9** [TeamAOF/All-of-Fabric-6#102]
When trying to open Quest this show
![image](https://user-images.githubusercontent.com/64946503/218263279-47e4bfca-eacc-448d-aa1e-42c29a685bb7.png)
My game crash but not the server when open FTB chunks 
Here is the crash log https://mclo.gs/HDtXJs6

**Comment by himhimbb9** [comment]
And the world gen is broken
![image](https://user-images.githubusercontent.com/64946503/218263734-60797327-560c-4e71-adb7-778a9f466cd2.png)
![image](https://user-images.githubusercontent.com/64946503/218263763-5ff577f9-39b6-45ea-b01e-bd9014c182f6.png)
![image](https://user-images.githubusercontent.com/64946503/218263790-c06ae655-ff59-48c4-9243-61c91220def8.png)
![image](https://user-images.githubusercontent.com/64946503/218263852-750560ff-ec28-4e38-a073-731934ebac2f.png)
![image](https://user-images.githubusercontent.com/64946503/218263896-7bf022e4-d5dc-42b1-afa0-0d48642a544d.png)
![image](https://user-images.githubusercontent.com/64946503/218263971-fee4e0ea-8016-40bc-8396-19adf1e3a741.png)
The world look so cursed

**Comment by Linguardium** [comment]
looks like a corrupted install. i suggest reinstalling the pack
