### ISSUE TITLE
Crash on Startup after updating to 1.4.1.

### ISSUE THREAD

**Issue by Wahad** [TeamAOF/All-of-Fabric-6#104]
Just updated to 1.4.1. after the server I am playing on did the same. My fellow players have not been having issues, but I can no longer launch the pack from GDLauncher after updating. 

Logs [here](http://www.asphyx.fr/door/zerobin/?3bf88014a8d29557#9wFe5AOKaZ3I+yZWMgMMs1nMbgWLngEBHM0kEuNOfM8=)

**Comment by hokomili** [comment]
Some of your mods aren't the same version as a 1.4.1 should have.
I suggest a clean reinstall.
