### ISSUE TITLE
[Bug] AE2 Autocrafting system producing Mana (Botania)? 

### ISSUE THREAD

**Issue by Keiron-Beadle** [TeamAOF/All-of-Fabric-6#106]
Hi, I was following a guide to produce a system that could detect when the stock of an item was low, and call for more to be crafted. It looks something like this...

![show](https://user-images.githubusercontent.com/56656042/218518551-0768a910-ef2a-4925-acde-b56f2e98d025.png)

- ME level emitter pointing towards an export bus
- Export bus has redstone card and crafting card
- Export bus is setup to export crafting tables
- ME Level emitter calls for crafts when Crafting table count < 5.
- Crafting table recipe is "4 spruce planks = 1 crafting table" substitutions enabled

<img width="1001" alt="status" src="https://user-images.githubusercontent.com/56656042/218517821-2804ace8-595f-458b-95e7-7c116a29bfe3.png">

After leaving it to run for 5 minutes~ the result is... strange

<img width="259" alt="Result" src="https://user-images.githubusercontent.com/56656042/218517990-66c40a2a-8271-4d39-a820-851af30ae4aa.png">

Needless to say the crafting tables aren't produced, and instead I find this mana in the ME interface. Possible I have messed something up, however given the strange output I thought it best to put it here in case this is a legitimate bug.

**Comment by Linguardium** [comment]
which version of the pack are you on? this was an issue with applied botanics but that was fixed quite some time ago (or at least it was supposed to have been, maybe this is a new issue)

**Comment by Keiron-Beadle** [comment]
I am on 1.4.2

**Comment by Keiron-Beadle** [comment]
![SoloWorld](https://user-images.githubusercontent.com/56656042/218524753-96fed5c3-832f-4ec5-b8c4-c3c73328fdb9.png)

To add, I tested this in a single player world (originally I was working on a server), and in this screenshot you can see planks are being "made" by the Molecular Assembler, but in the ME Interface Mana is showing up. 

Here is the test setup I made

![test](https://user-images.githubusercontent.com/56656042/218525230-c95c3252-0237-4579-a1c0-65b83f5b7376.png)

**Comment by ImAK9** [comment]
Which version of Applied Botanics do you have?

**Comment by Keiron-Beadle** [comment]
Applied Botanics : 1.4.1

**Comment by ramidzkh** [comment]
Can you try the applied botanics jar inside this zip: https://github.com/ramidzkh/Applied-Botanics/suites/11060085123/artifacts/562312684

**Comment by Keiron-Beadle** [comment]
> Can you try the applied botanics jar inside this zip: https://github.com/ramidzkh/Applied-Botanics/suites/11060085123/artifacts/562312684

Looks like that fixed the issue for me (at least in single player)

**Comment by ramidzkh** [comment]
@ImAK9 Fixed in Applied Botanics 1.4.2

**Comment by ImAK9** [comment]
Fixed in pack version 1.4.4
