### ISSUE TITLE
Need help on updating my AOF6 server

### ISSUE THREAD

**Issue by anerrorpage** [TeamAOF/All-of-Fabric-6#107]
Need help on updating my AOF6 server, tried deleting the serverstarter.lock but after running the server again, it just download the mods and the version is still 1.3.0
want to update it to 1.4.2

my server system is running ubuntu 22.04 LTS

**Comment by SomeAspy** [comment]
Sometimes the autoupdater just doesn't want to work. You can update manually by moving your world folder to a safe place, deleting the entire install, and fresh installing the pack. You can move your world folder back and everything should be properly updated.
