### ISSUE TITLE
[Suggestion] Replace Extra Thicc Packets with XL Packets Fabric

### ISSUE THREAD

**Issue by Linguardium** [TeamAOF/All-of-Fabric-6#109]
https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric/files/4110462

Extra Thicc Packets seems to be missing the encoder change that is required for encoding packets that are over size. the XL Packets update allows it. 

ETP is also an unofficial update and improvement to XLPackets and states "it will stop being updated if/whenever I am made aware that the original updates to 1.19+" which happened last November

**Comment by ImAK9** [comment]
I'll make sure to have it replaced with next release.

**Comment by ImAK9** [comment]
Replaced in 1.4.3
