### ISSUE TITLE
Randomly unable to attack mobs

### ISSUE THREAD

**Issue by d-jones99** [TeamAOF/All-of-Fabric-6#11]
Running AOF6 server latest version (0.1.4) and 2 of us seem to be unable to attack mobs at random points when playing. Any suggestions of how to fix?

**Comment by Clonephaze** [comment]
FTBChunks was affected in this update, any chance it happens when inside claimed chunks? Nothing else changed in this update that would affect that kind of thing afaik.

**Comment by dandin87** [comment]
FTB chunks was not changed. giving a block a tag is not going to do that. There have been some instances of this reported before, but not sure how to reproduce to debug it.

**Comment by ImAK9** [comment]
Do any of you two recall what you were doing when this started happening?

**Comment by Annabxlla** [comment]
I am now having the same bug, it just happened out of the blue, my friend is still able to attack whilst I am unable to attack or even shoot a bow.

**Comment by ReapsAndCreeps** [comment]
Not 100% on this,  but it seems to occur after using the steam powered drill from Modern Industrialization. I think it might occur if your hit while breaking blocks or just in general after using it.
