### ISSUE TITLE
Steam mining drill crashes the game

### ISSUE THREAD

**Issue by CaleBolota** [TeamAOF/All-of-Fabric-6#110]
When I just hover the cursor on the steam mining drill from industrial revolution my game crashes and it shows the following error message:
The game crashed whilst rendering screen
Error: java.lang.IllegalArgumentException: Unknown TooltipComponent

code: -1

**Comment by Linguardium** [comment]
update TieredZ

**Comment by Jyrz** [comment]
If the server is 1.4.1, will updating my modpack break anything?

**Comment by Linguardium** [comment]
yes. you cannot update to 1.4.2 due to changes in content, but updating only tieredZ does not change content, and works clientside to stop the crashing

**Comment by Jyrz** [comment]
Ok, cool. Thanks.

**Comment by CaleBolota** [comment]
> yes. you cannot update to 1.4.2 due to changes in content, but updating only tieredZ does not change content, and works clientside to stop the crashing

im using the curse forge to load the pack, so how can i update tieredz?

**Comment by Jyrz** [comment]
Same way you would usually do it, but you just need to open the game files from the Installation tab in the MC launcher after you launch the modpack from CurseForge

**Comment by ImAK9** [comment]
I'm closing this issue as fixed in 1.4.2
