### ISSUE TITLE
[Bug] Lassos don't seem to do anything?

### ISSUE THREAD

**Issue by Elfinlocks** [TeamAOF/All-of-Fabric-6#111]
Not sure if this is just me, but the Lassos don't seem to work. I tried using the Golden Lasso to capture a vanilla Minecraft Cow via right-clicking the mob multiple times with the Lasso to no avail. Has anyone else encountered this issue? I switched to Creative and it seems the Diamond Lasso also does not work.

**Comment by Linguardium** [comment]
they dont work sometimes with mobs that also have a right click interaction. try moving out and into range, aim at the bottom of the hitbox, etc
