### ISSUE TITLE
Some SimplySwords Unique Weapons do not accept Runic Tablets in Reforge Gear menu on Anvil

### ISSUE THREAD

**Issue by Travynn1** [TeamAOF/All-of-Fabric-6#113]
When attempting to reforge the Rarity on some SimplySwords Unique weapons, the Runic Tablet placed in the left slot does not seem to register with the UI, and the Reforge button does not become clickable/active. This prevents these weapons from being reforged.

This does not appear to happen with all unique weapons -- so far, I have seen this happen with the Soulkeeper (common, if that matters) and the Livyatan. However, I was able to properly reforge an Arcanethyst with Runic Tablets and a Bramblethorn with wood, so it does not appear to be impacting all of the unique weapons.

![image](https://user-images.githubusercontent.com/125541157/219294019-7fb952a2-b9a5-4e78-ba79-f39e5531fc91.png)

**Comment by ImAK9** [comment]
Make sure the weapon is fully reparied

**Comment by Travynn1** [comment]
Ah dang yep that it is -- my bad. Didn't think to try that and it didn't mention it anywhere that I saw.

Closing. Thank you!
