### ISSUE TITLE
Geode Automation not working with AE2 Annihilation planes

### ISSUE THREAD

**Issue by Jamman360** [TeamAOF/All-of-Fabric-6#117]
It would be nice if all geodes were treated as certus quartz, in that it only harvests once it becomes a cluster, rather than as soon as a bud grows. Specifically, we are trying to set up a nether quartz farm and are unable to make it look like/fit the same template as the certus one due to current mechanics.

**Comment by Nitrogen8809** [comment]
I'm your man.
Here's the plan:
1. Use Silk Touch to gather 64 of Nether Quartz Ore.
2. Obtain the following from the Industrial Revolution Mod:
     a. Mining Rig Computer
     b. Mining Rig Drill
     c. Data Card
     d. Data Card Encoder
3. Throw the Quartz Ore In the Data Card Encoder w/ the Data Card.
![image](https://user-images.githubusercontent.com/31896979/219892328-b8e3eeb5-57a5-4392-8887-90608378c315.png)

4. Put the Data Card In the Mining Computer.
![image](https://user-images.githubusercontent.com/31896979/219892702-402c70ae-5097-4209-aeca-a1c809d3ffb0.png)

5. Obtain **dummy** quartz.
![image](https://user-images.githubusercontent.com/31896979/219892807-40820d4e-eb04-4d4c-aaf8-14e789e4413e.png)

Here's a photo of what my setup looks like:
![image](https://user-images.githubusercontent.com/31896979/219892953-55e9b4a9-9b20-48e1-b909-e91f2b64a765.png)

I think the whole Annihilation Pane + Certus Quartz Farming is exclusive to AE2.
Trust me, you don't want it to be like that.

If you're wondering how I obtained the Netherite to create all of this - there are bases on Venus that sometimes have little Nether Mine rooms. If you can obtain 64 blocks of Ancient Debris, you can also multiply it in the Mining Rig.

**Comment by Jamman360** [comment]
Thanks for this! one of my friends has the mining drill but it was plan b. I did manage to get the crystal farm working though, one if ound out you can enchant the annihilation plates! throw silk touch on them and set them to harvest the nether quartz clusters, then have a single formation/annihilation (with fortune 3 this time) to break the clusters 👍
