### ISSUE TITLE
(Suggestion) There should be a small warning about attempting to craft "the perfect compound?" from spectrum. 

### ISSUE THREAD

**Issue by Clonephaze** [TeamAOF/All-of-Fabric-6#12]
Spoilers ahead if you haven't progressed through the mod:

The craft "the perfect compound", or "midnight aberration" once you've made it once, is incredibly destructive to the surroundings of your fusion altar. The in-game guide nor the in-pack quest list say or even suggest that this might be the case. All of my plants, trees, tons of my dirt, part of my pond, so much destroyed. That isn't cool and is incredibly frustrating that all my decorations are just gone now because of a craft required to progress though the mod. You can see the destruction in the pictures. The liquid that spawns breaks things like water does, but also sets wooden things on fire and eats cobble and dirt. 
![2022-11-23_12 24 29](https://user-images.githubusercontent.com/6809805/203641577-2f9b742a-03b7-4948-ae19-cc756d8b0d5a.png)
![2022-11-23_12 24 54](https://user-images.githubusercontent.com/6809805/203641580-80d2a22b-688b-4b36-b6be-2ca555ffbca5.png)
![2022-11-23_12 24 13](https://user-images.githubusercontent.com/6809805/203641564-b2e72472-fdca-4f5c-865a-5b1d0682a233.png)
![2022-11-23_12 24 17](https://user-images.githubusercontent.com/6809805/203641571-dfed2b8b-acab-46b9-9a5d-0f31eec78971.png)

**Comment by Linguardium** [comment]
The in-world story of Spectrum is great, and this plays into that "discovery" style story. I think that mentioning mythology might be to obscure for people to understand the reference. To avoid this it might be worth mentioning it being important to use a strong foundation, just in case of accidents, in the fusion shrine quest.  Then you can reference the accidents a little up to that point, just to stress the importants of using strong blocks, maybe give a range (16 block radius at worst i believe?)

**Comment by Clonephaze** [comment]
Yeah, I totally loved discovering that a mod that has been otherwise benign up to this point was gonna turn left real quick and destroy a bunch of decorating I did with no warning of any kind at all. That sure was great lol. Don't get me wrong, the discovery up to that point was awesome. I was having a lot of fun, this immediately detracted all that fun for me. I don't get to play a super long time, to see that roughly 45 minutes of trying to "pretty up" the area was obliterated by some dumb craft was irritating and not fun at all. I think a simple "due to the unknown forces at work, it might be better to build your fusion altar away from your work area for now" would solve all issues without giving anything away except that something destructive was gonna happen.

**Comment by Linguardium** [comment]
I would love to see some guide related storyline on this too, like the player slowly realizing that maybe some of the forces they have been invoking to make faded and such might be more destructive than they thought.  It seems the story is the player throwing themselves into the magic with wild abandon

**Comment by Clonephaze** [comment]
That would be cool, maybe a suggestion for their github. I would love it if this pack just added a line to their own quest list about it.

**Comment by Linguardium** [comment]
It isnt really for no reason, you directly initiate the cause, watch the cause, lament at the destruction that you unwittingly just unleashed... you know what did it and the in-game guide changes to let you know you oopsed, but you dont really have another choice :(

**Comment by Clonephaze** [comment]
Thats true, I should say "for seemingly no reason" since you don't get the reason until after the destruction happens.

**Comment by DaFuqs** [comment]
done 👌
