### ISSUE TITLE
Everytime I use an item that requires a Right Click - It goes into my Wireles Terminal.

### ISSUE THREAD

**Issue by docHP** [TeamAOF/All-of-Fabric-6#121]
Wireless Terminal ends up taking whatever item I am using to right click.

Some of the SimplySwords, Some guidebooks, Flint and Steel, or Hoes, etc.

I have tried looking through my own configs and I don't see anything that could be causing this.

My other friends don't seem to have this issue though so I am unsure of where to even begin looking.

The Wireless Terminal actually ends up going into itself when I right click to use it.

**Comment by Bellabong** [comment]
Your autorefill setting is on, this is how it behaves with items like the one you've described
