### ISSUE TITLE
[Suggestion] Add Hearty Trinkets Mod

### ISSUE THREAD

**Issue by Traverse-Joe** [TeamAOF/All-of-Fabric-6#123]
I watch a YouTuber named Lashmak and he added the mod and it works well with the pack and with new features in the works I’m sure  it would fit well in the All of Fabric style play thanks for considering it’s been updated for 1.19.3 when ever that big update occurs in the mean time a stable 1.19.2 works fine 

https://www.curseforge.com/minecraft/mc-mods/hearty-trinkets

**Comment by Linguardium** [comment]
the most recent update added spice of fabric, which allows gaining hearts through eating unique foods, which provides a similar function through another mechanism. IMO hearty trinkets would be overshadowed by just eating more random food
