### ISSUE TITLE
Toast Manager is gone from curseforge

### ISSUE THREAD

**Issue by gregest** [TeamAOF/All-of-Fabric-6#124]
That's it, that's the issue. Toast Manager can't be downloaded because it has been removed for some reason, meaning the pack can't be downloaded either

**Comment by Linguardium** [comment]
https://www.curseforge.com/minecraft/mc-mods/toast-manager/files/3953164

**Comment by gregest** [comment]
That's weird, when I made this post whenever I tried to open the mod's page it would 404, must have been beta curseforge or I'm not sure

**Comment by BobbyWibowo** [comment]
Can confirm that it happens to me sometimes too
It appears that they're forcefully redirecting you to the beta website when the main site is under heavy load and such ([source](https://curseforge-ideas.overwolf.com/ideas/CF-I-4130))
