### ISSUE TITLE
Machine Upgrade Duplication

### ISSUE THREAD

**Issue by Nitrogen8809** [TeamAOF/All-of-Fabric-6#126]
CTRL-Clicking any machine upgrade while they're in a Modern Industrialization machine will duplicate them.

I'd show a gif illustrating this, but I think this works just as well...
![image](https://user-images.githubusercontent.com/31896979/220986321-0b3f4b04-0eb3-476c-b1ad-936bf522c16d.png)
I regret nothing.

A part of me genuinely isn't sure if this is a bug with the modpack or Modern Industrialization - but I refuse to believe I'm the first one to find this.
Unless this can be replicated easily by other users (which I know it may be) then there's a chance this is just a strange issue with my friends server.

**Comment by Linguardium** [comment]
does this happen without InventoryEssentials

**Comment by alex256z** [comment]
Same duplication when Ctrl-click on items in the MI Configurable Chest.

**Comment by Nitrogen8809** [comment]
This has been fixed as of 1.4.4.
