### ISSUE TITLE
Crafting Bug

### ISSUE THREAD

**Issue by Gamercat09** [TeamAOF/All-of-Fabric-6#127]
Some things, for some reason, i cannot craft. i have all of the materials, i just cannot craft it.(images below)
![2023-02-23_22 13 04](https://user-images.githubusercontent.com/103867279/221090167-0244880e-18f5-4277-b8ca-5a8e93161420.png)
![2023-02-23_22 13 21](https://user-images.githubusercontent.com/103867279/221090188-8919f41d-5d10-4265-beed-cce4d9f1444f.png)

**Comment by Linguardium** [comment]
cannot reproduce on my end. is this a server or a single player?

**Comment by Gamercat09** [comment]
Both.

**Comment by Linguardium** [comment]
sounds like a broken install. reinstall the pack and copy your save over. if the server also has the same problem, be sure to reinstall the server from the official server pack download

**Comment by Gamercat09** [comment]
That Didn't Work.

**Comment by Gamercat09** [comment]
Edit: I'm Stupid, there was no bug. I will not elaborate further

**Comment by Vadym-Dworkin** [comment]
@Gamercat09 I have a same problem, how do you fixed it? Thanks
