### ISSUE TITLE
Re-Forging And Prefix Question/bug(maybe)

### ISSUE THREAD

**Issue by Gamercat09** [TeamAOF/All-of-Fabric-6#128]
In the second tab of the Anvil interface, you can re-forge your gear. For some reason, I cannot re-forge anything. I am either unsure how this works, It is purposely prevented, or it is a bug.( example:
![2023-02-25_22 51 00](https://user-images.githubusercontent.com/103867279/221393005-4d1a6c06-b78d-47e0-aa00-935bd6b6de9d.png)
 )

**Comment by Jamman360** [comment]
Reforging also requires amethyst in the 3rd slot

**Comment by Gamercat09** [comment]
gotcha.

**Comment by Gamercat09** [comment]
It still doesn't work.
![2023-02-26_12 06 05](https://user-images.githubusercontent.com/103867279/221428217-11cbd45b-9024-4612-a933-1445b801ce90.png)

**Comment by AlienXAXS** [comment]
It would seem that it's not possible to reforge paxels, I'll do some digging to find out more.

**Comment by Linguardium** [comment]
make sure items are fully repaired, you cannot reforge something that is damaged

**Comment by AlienXAXS** [comment]
> 

Even spawning in a brand new paxel doesnt allow it to be modified by Tiered.

It would seem the Tiered mod does not see the paxel as a item that's a valid option, as other items you can shift+click into the anvil GUI, Paxels you cannot.
