### ISSUE TITLE
Soul Elytra should also be equipable in the Cape slot, just as normal Elytra

### ISSUE THREAD

**Issue by ShadedPL** [TeamAOF/All-of-Fabric-6#13]
Currently you cannot equip the Soul Elytra in the Cape slot, like you can with the vanilla Elytra. Not sure if this is intended but my suggestion is to have it also equipable in the Cape slot, especially as this is an end-game item, after killing the warden and all the Deeper and Darker mobs.
Thanks for taking it into consideration, also please let me know if this is configurable by you or the mod author.

**Comment by ImAK9** [comment]
This would be on the mod author to add compat with Trinkets API

**Comment by ShadedPL** [comment]
https://github.com/KyaniteMods/DeeperAndDarker/issues/106 made an issue on the mod page
