### ISSUE TITLE
(suggestion) Better End and Mythic metals?

### ISSUE THREAD

**Issue by Gamercat09** [TeamAOF/All-of-Fabric-6#131]
2 Really Cool Mods that i think would Improve The Overall Experience of the modpack. (Links below to each)
[https://www.curseforge.com/minecraft/mc-mods/betterend]
[https://www.curseforge.com/minecraft/mc-mods/mythicmetals]

**Comment by Linguardium** [comment]
![image](https://user-images.githubusercontent.com/61733861/221742632-f7f5bff5-fa7b-4ff7-9a82-7a68a9b3c8e3.png)
