### ISSUE TITLE
[Enhancement] DML quest should clarify change in simulation chamber

### ISSUE THREAD

**Issue by Linguardium** [TeamAOF/All-of-Fabric-6#132]
previous DML iterations allowed simulation chamber to simulate mob killing, and as a result to level up data models.  This behaviour was reversed in the 0.5.8 beta.

The data models now decrease with each simluation, downgrading the models and requiring farming mobs to sustain the setup

**Comment by EmberAnimus** [comment]
Good news is that an update to the DML mod a couple of days ago added a config option for this. Curious if the modpack will change it (default is increase by 1). For now I manually updated the mod and changed the config option to 0, as I found loosing data to be annoying.
