### ISSUE TITLE
Missing Supplementaries textures in v1.4.4

### ISSUE THREAD

**Issue by mtakemoto** [TeamAOF/All-of-Fabric-6#135]
Wall lanterns and hanging signs fail to load with debug textures displayed.  Seems to only affect some Supplementaries blocks.  They're tracking this issue in their repository and seems to be a conflict with the new Connected Textures mod (CTM) that got added in 1.4.4.

https://github.com/MehVahdJukaar/Supplementaries/issues/395

I attempted to hotfix this by removing CTM + Chipped on the server-side but that didn't do it.
Submitted to `#bug-reports` in the Discord, too

![2023-03-03_13 46 48](https://user-images.githubusercontent.com/3156196/222864374-1caf2d06-4be8-4b8c-b8a7-d925317d722a.png)

**Comment by ImAK9** [comment]
Fixed in 1.4.4
