### ISSUE TITLE
Horizontally mounted hanging blocks from supplementaries show missing textures

### ISSUE THREAD

**Issue by Spaccce** [TeamAOF/All-of-Fabric-6#137]
After updating to 1.4.4, all of our hanging signs and hanging lanterns that are horizontal show missing textures, but when you go inside you see that they are still there.
![2023-03-04_17 10 14](https://user-images.githubusercontent.com/107164194/222936364-0a70375c-2c3c-4d66-a3a3-47361b37490e.png)
![2023-03-04_17 10 39](https://user-images.githubusercontent.com/107164194/222936365-a22b7237-e6f9-4f22-81d5-9b3ac39b3fb5.png)
![2023-03-04_17 11 00](https://user-images.githubusercontent.com/107164194/222936367-c89d7f9b-42d7-439f-b31f-f5cfc72836f7.png)
![2023-03-04_17 11 51](https://user-images.githubusercontent.com/107164194/222936369-ea86c608-d834-41f1-8672-14b54e427bd5.png)

**Comment by ImAK9** [comment]
Fixed in 1.4.5
