### ISSUE TITLE
I cant open backpack inventory in fabric modpack

### ISSUE THREAD

**Issue by krjencik** [TeamAOF/All-of-Fabric-6#138]
Hi, there is my little issue:
(from the mods issue page)

I somehow equipped the backpack, but cant unequip it or use it.
changed key to g still doesnt work.
Im playing All of fabric 6 modpack.

**To Reproduce**
1. ...
I dont know how to reproduce this.. maybe trying the modpack out and equip the backpack? I dont even know how did i equip it...

**Expected behavior**
Be able to access the backpack inventory. To be able to unequip and use it.

**Required informations (please complete the following information):**
 - Mod version: [For example: 1.16.4 - 5.3.7] 1.19.2 - 8.2.14
- Mod Loader: [Fabric or Forge] Fabric

**Comment by krjencik** [comment]
this modpack version: 1.4.4

**Comment by NightFuryStrike** [comment]
Greetings, I was able to get around this bug by changing the key to ";" or numpad 0
Hope that helps!

**Comment by alex256z** [comment]
You need to remap backpack key bindings, because if something is mapped to the same key, one of them might not work.
In my game "Travellers Backpack" key is "N", and "Inmis" backpack key is "B".

**Comment by krjencik** [comment]
ok ty

**Comment by krjencik** [comment]
now it works :))
