### ISSUE TITLE
Missing Lantern Texture - Side Connect

### ISSUE THREAD

**Issue by LexsiJ** [TeamAOF/All-of-Fabric-6#139]
Item: Lantern
Mod: (idk - thought this was vanilla feature but I cannot remember)
Placement: connected to side of block (eg wall)
Issue: Displays as pink and black block
![AOF6_Lantern_missingtexture_1 4 4](https://user-images.githubusercontent.com/42349498/222979367-6b59be8c-dd8a-4f42-aa94-2a625f96d70e.PNG)

Edit to add: Visual tag is "Wall Lantern"

**Comment by Lgmrszd** [comment]
Issue can be tracked here: https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/633

**Comment by ImAK9** [comment]
Fixed in 1.4.5
