### ISSUE TITLE
Server installer does not function

### ISSUE THREAD

**Issue by Zacknac** [TeamAOF/All-of-Fabric-6#14]
Testing on Arch Linux 6.0.2
Starter jar file is corrupted, coming in at a whopping 0 bytes
![image](https://user-images.githubusercontent.com/77754097/204112298-9d1314f5-cc31-4be0-829c-8fd9bba2f617.png)
![image](https://user-images.githubusercontent.com/77754097/204112305-658709e1-731b-4b42-8b80-d5b4d04eeb19.png)

**Comment by thinkgeek23** [comment]
I am having the same issue

**Comment by Linguardium** [comment]
its not 0 bytes on my side, tested yesterday. sounds like it failed to download it

**Comment by Zacknac** [comment]
Tried on both my local PC and a separate server, neither worked
Download link is probably just down

**Comment by Linguardium** [comment]
I tested immediately after posting and it worked for me again. I would suggest you download the files on your local machine and copy them up to the server since the server is having a problem downloading files

**Comment by Zacknac** [comment]
Neither my PC or the server worked, but I'll try it in the morning

**Comment by ringprod** [comment]
If anyone else is having this issue, open the startserver.sh or startserver.bat file and look for the server starter jar link it should look something like https://github.com/TeamAOF/ServerStarter/releases/download/v2.4.0/serverstarter-2.4.0.jar download the jar file and place it in the server directory and run the script again. It will now install all the mods and set everything up.
