### ISSUE TITLE
Multiple conflicting recipes for ores in crushing wheel

### ISSUE THREAD

**Issue by sreny1** [TeamAOF/All-of-Fabric-6#141]
there are multiple recipes for many ores in the create crushing wheel
this is just confusing..
![image](https://user-images.githubusercontent.com/101481389/223285547-fb998668-d11f-48c7-b76c-ef29e98b1ceb.png)

**Comment by libjared** [comment]
I can confirm this is still an issue.

**Comment by libjared** [comment]
This is still an issue in 1.8.2. Please reopen.
