### ISSUE TITLE
small dust and tiny dust recipe from dust conflicting

### ISSUE THREAD

**Issue by sreny1** [TeamAOF/All-of-Fabric-6#144]
pack version: 1.4.4
when trying to craft tiny dust from dust and there also being a recipe for it into small dust, then you always end up crafting the small dust
for example this happens with chromium and titanium
![image](https://user-images.githubusercontent.com/101481389/224464671-5c8133f1-7227-4f68-b618-8a365270bb62.png)

**Comment by Nitrogen8809** [comment]
Yea, this can be a little irritating.
I recommend using a Macerator on nuggets of metal. It's more tedious than a 1-click craft, but it's still a 1:1 craft.
I also recommend crafting a lot, since you'll need a good bit of small chromium dust for several different things.

**Comment by ImAK9** [comment]
This was added/fixed in 1.4.5
