### ISSUE TITLE
Own Server has Problems with generating the End

### ISSUE THREAD

**Issue by JHKuck142** [TeamAOF/All-of-Fabric-6#146]
Hello Guys. We reached the point on our server to visit the end but when we want to enter the end through the portal the whole server times out. For a short time you can see small parts of the main island but only a few chunks.

**Comment by Deadpickle872** [comment]
i have the same issue currently with my server. when entering the end it times out the server, seems to be a memory problem. i was able to generate the end in single player then transfer my world back to the server. this seems to have resolved my inability to enter the end, albeit with some clear stability issues, leaving the end too quickly after entering still results in a crash. again seems related to a lack of memory.

**Comment by JHKuck142** [comment]
@Deadpickle872 Thx a lot. We also used a singleplayer generated end and it worked. Hope it will generate the rest ;D

**Comment by AriBerisha** [comment]
Samething here!

**Comment by ImAK9** [comment]
fixed in 1.5.1
