### ISSUE TITLE
Server is consistantly lagging 

### ISSUE THREAD

**Issue by peachytea** [TeamAOF/All-of-Fabric-6#148]
I've been having issues with the AOF 6 server I'm running off my computer. No matter how much ram I've allocated, the server is always running 40 to 50 ticks behind consistently. 

I ran the Spark profiler, here are the results: https://spark.lucko.me/kWZm0f0aDE

I've also done a fresh reinstall of everything and the issue still prevails. I'm at a loss here, could it be one of the mod packs causing this?

**Comment by dandin87** [comment]
40 to 50 ticks behind shows up all the time and is nothing to be concerned about.
Spark shows you have 19.98 tps over the last 15 min. So nothing wrong there.
