### ISSUE TITLE
Mining Gadget MK1 cannot be crafted, rendering Tools and Armory quest impossible to complete

### ISSUE THREAD

**Issue by Justicetom21** [TeamAOF/All-of-Fabric-6#149]
The Mining Gadget MK1 is impossible to craft. All three tiers of the Mining Gadget use the same recipe and the recipe automatically crafts the MK3. While this wouldn't normally be an issue, the Mining Gadgets quest specifically needs a Mining Gadget MK1 to complete, rather than any one of the three.
![image](https://user-images.githubusercontent.com/97956083/225895311-4a8ced92-0f47-4dfe-8466-bca2fc514ddf.png)

![image](https://user-images.githubusercontent.com/97956083/225895178-8f248e1b-7ad7-4ce7-af03-20e4ad2e67c9.png)
![image](https://user-images.githubusercontent.com/97956083/225895219-caaa1355-51f0-4b4b-8a54-f81110198ed5.png)

**Comment by ImAK9** [comment]
This will be fixed in 1.5.1

**Comment by ImAK9** [comment]
fixed in d6a634b0877ad510e67ea8928397bfdba515814f
