### ISSUE TITLE
Game Crash when watching the video of how to use basin in Create Mod

### ISSUE THREAD

**Issue by StevenUST** [TeamAOF/All-of-Fabric-6#151]
When I press "w" to watch the video of how to use basin in Create Mod, game crashes and the error code is generated as follow:

The game crashed whilst ticking screen
Error: java.lang.ClassCastException: class com.simibubi.create.foundation.ponder.PonderWorld cannot be cast to class net.minecraft.class_2791 (com.simibubi.create.foundation.ponder.PonderWorld and net.minecraft.class_2791 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @58134517)

Exit code: -1

**Comment by D3DK3T** [comment]
happens also with Mechanical Plough

**Comment by LuciustheDragon** [comment]
This is an issue with Lithium 0.11.0. Try replacing it with Lithium 0.11.1 (make sure it's the one for 1.19.2). I had the same issue and this fixed it.

**Comment by svtz** [comment]
yeah, Lithium update solves the issue

**Comment by ImAK9** [comment]
fixed in 1.5.1
