### ISSUE TITLE
Game crashes while exploring the nether 

### ISSUE THREAD

**Issue by FluxUmbreon** [TeamAOF/All-of-Fabric-6#152]
Description: Accessing LegacyRandomSource from multiple threads

[crash-2023-03-18_21.40.13-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11011601/crash-2023-03-18_21.40.13-server.txt)
[crash-2023-03-18_21.49.09-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11011602/crash-2023-03-18_21.49.09-server.txt)
[crash-2023-03-18_21.31.29-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11011603/crash-2023-03-18_21.31.29-server.txt)

**Comment by ImAK9** [comment]
fixed in 1.5.1
