### ISSUE TITLE
killing a boss with quantum sword doesnt trigger quest completions

### ISSUE THREAD

**Issue by sreny1** [TeamAOF/All-of-Fabric-6#154]
whenever killing a boss needed for quests with quantum sword it does not count for quest completion
unsure if this is a mod or pack issue, so i put this here :)

**Comment by fridayd** [comment]
I believe that is just the nature of the quantum sword—using it is essentially the same as using a “/kill” command, so there’s not drops or credit to the player.

**Comment by sreny1** [comment]
i mean i can stand there in quantum armor (invincible) and hit the boss for a minute or one hit it with the quantum sword.
also you get the loot for the boss and get achievements too, just not the quests
