### ISSUE TITLE
terra shatterer quest wont complete

### ISSUE THREAD

**Issue by sreny1** [TeamAOF/All-of-Fabric-6#157]
i made and filled up this terra shatterer to the limit and quest wont complete
i tried many things including crafting a new terra shatterer and transfering the mana, but nothing worked :(

![image](https://user-images.githubusercontent.com/101481389/226938080-de0483b4-1bb3-4c9d-b6db-cbecbcd3cb53.png)
![image](https://user-images.githubusercontent.com/101481389/226938543-0c69aac4-1f86-43e7-992d-6e58804faa33.png)

**Comment by sreny1** [comment]
dug into this issue a bit, it seems to be because of the "RepairCost: 0" nbt value in the required quest item

when you craft a terra shatterer and fill it up it doesnt have this nbt value:
![image](https://user-images.githubusercontent.com/101481389/227389753-a6fdfc17-3990-482c-80be-572141966f00.png)

**Comment by Savior10K** [comment]
changing and unchanging the name in an anvil completed that quest for me so i think thats a way to get that nbt

**Comment by sreny1** [comment]
stil a bug in my opinion

**Comment by ImreLammers** [comment]
Combining it with a Elementium Pickaxe to get the bonus effect adds 1 more NBT tag than the required quest item therefore not being able to complete the quest. 

Not sure if it's possible to have an either/or check for both NBT values.

**Comment by Zackatron** [comment]
Combining it with a Elementium Pickaxe to get the bonus effect adds 1 more NBT tag than the required quest item therefore not being able to complete the quest.

Not sure if it's possible to have an either/or check for both NBT values.
