### ISSUE TITLE
farmers delight straw seems unobtainable

### ISSUE THREAD

**Issue by sreny1** [TeamAOF/All-of-Fabric-6#158]
REI lists many ways to get straw, but none of them seem to work or the item it uses seems to have the same issue (like wild rice)
without that i cant seem to craft the basket, which is needed for a quest

**Comment by hokomili** [comment]
You can use a knife from farmer's delight on wheat to get straw (left click).

**Comment by sreny1** [comment]
> You can use a knife from farmer's delight on a fully grown wheat to get straw (left click).

can confirm, using a knife works. wish REI told me to use a knife to get that :)
