### ISSUE TITLE
Cannot Craft Bronze ingot in Modern Industrialization

### ISSUE THREAD

**Issue by Lathler** [TeamAOF/All-of-Fabric-6#159]
as the title says the only one way you can get from is from trading. every time i want to craft bronze ingot from modern industrialization it's always go back to tech reborn. i need it for continuing the quest because tech reborn bronze can't register the quest
![bronze](https://user-images.githubusercontent.com/128730450/227274960-c442336f-4791-4bd8-8087-3bc7fe12e18a.PNG)

**Comment by dandin87** [comment]
You want to make bronze dust. With copper and tin dust in the crafting grid. Then smelt that into the ingot...

**Comment by Lathler** [comment]
already tried and it's always gets converted to tech reborn. do i need to smelt it in modern industrialization furnace or smth?

**Comment by sreny1** [comment]
why do you need specifically MI bronze?

**Comment by continuum-kevin** [comment]
I am having same problem. You specifically need MI bronze or the quest won't progress.
