### ISSUE TITLE
Only vanilla ores generate from Orechid

### ISSUE THREAD

**Issue by jpenilla** [TeamAOF/All-of-Fabric-6#161]
Recipes need to be added via data pack

https://github.com/VazkiiMods/Botania/tree/1.19.x/Xplat/src/generated/resources/data/botania/recipes/orechid

**Comment by jpenilla** [comment]
I modified RoughlyEnoughResources locally to Orechid recipes, here's the data pack it created:

[pack.zip](https://github.com/TeamAOF/All-of-Fabric-6/files/11128613/pack.zip)

And here's some screenshots from testing (50/50 stone & deepslate)
![image](https://user-images.githubusercontent.com/11360596/229269809-b05f676e-f5ec-412f-9161-ac9b7d0e5e72.png)

![2023-03-31_23 32 09](https://user-images.githubusercontent.com/11360596/229269827-5c1858dd-1d9b-42a3-89b7-aecc66dfa0d6.png)

**Comment by FarrunDragon** [comment]
Can this datapack be server side only or does it need to be client and server?

**Comment by jpenilla** [comment]
it's only needed on the server
