### ISSUE TITLE
The game stops responding to anything I try to do in-game

### ISSUE THREAD

**Issue by nefariouslegion** [TeamAOF/All-of-Fabric-6#163]
I've noticed every so often the game stops working properly. I cease being able to open anything (like chests, machines, etc.). Chunks also stop loading. Then if I try and save the game and return to the menu it just stays stuck on "Saving World" with the tips still alternating fine. This ofc is a single player world. I'm then forced to close the game via Task Manager.

I have allocated 12GB of RAM to the game via CurseForge settings and I'm running on a Ryzen 9 5900X and RTX 4070 Ti. 

I'm hoping someone can help fix this issue

**Comment by dillontkh** [comment]
I experienced this too, but after going into the prison portal.
Here's my logs https://mclo.gs/ZQ8p7Jq
