### ISSUE TITLE
Mining gadget infinity power

### ISSUE THREAD

**Issue by aruss69xd** [TeamAOF/All-of-Fabric-6#165]
It worked on 1.3.0, after that smth broke.

**Comment by n3rdcoach** [comment]
AOF6 - 1.5.0:  Same problem here.  Can charge the mining gadget normaly, but after that, it just keeps its power as if it is a creative tool

**Comment by Bellabong** [comment]
What probably broke it is the fix for the max charge. That config option doesn't do exactly what it says it does.

**Comment by aruss69xd** [comment]
changed that back to 1kk and it was still the same.

Posted issue on mining gadgets github, but they didnt anwser yet.

**Comment by csBlackWolf** [comment]
I see you posted it on the GitHub from the original mod, what is for Forge and not Fabric. This modpack is using a port of the mod. 

https://www.curseforge.com/minecraft/mc-mods/mining-gadgets-fabric

I did the same mistake and just now realised it myself that the mod used here is not the original mod. 😅

**Comment by Jaakurin** [comment]
Updated to version 1.7.1 and the issue still persists.

**Comment by libjared** [comment]
This is still an issue in 1.8.2.
