### ISSUE TITLE
Broken recipes due to missing AE2 certus quartz ore in 1.19+

### ISSUE THREAD

**Issue by James103** [TeamAOF/All-of-Fabric-6#169]
The block `ae2:quartz_ore`, as originally defined by Applied Energistics, no longer exists starting with 1.19 due to a rework of the Certus Quartz processing system by that mod.

This means custom recipes defined by the modpack for the Pulverizer and Industrial Pulverizer from Tech Reborn and Industrial Revolution no longer work but still show up in REI.

Originally found in All of Fabric 6 1.5.0, but this persists in the latest version 1.5.1 as the relevant code hasn't changed.

**Comment by fridayd** [comment]
I'd suggest changing the issue title... as you layed out, the missing ore is not the problem, the recipes are.

**Comment by JoelZBub** [comment]
The manner of obtaining Certus Quartz has changed in 1.19+. 
https://appliedenergistics.github.io/getting-started
```The primary way of obtaining quartz is from breaking quartz crystal clusters. These grow on budding quartz in a way that is similar to Vanillas amethyst. Budding quartz decays when growing buds, but can be recharged using [Charged Certus Quartz Crystal](https://appliedenergistics.github.io/features/crystals) in a puddle of water. New budding quartz can be created the same way by using a [Certus Quartz Block](https://appliedenergistics.github.io/features/decorative-blocks/certus-quartz).
Meteorites will sometimes contain a flawless budding quartz.```
