### ISSUE TITLE
Vinery Out of Date

### ISSUE THREAD

**Issue by Kinnickinick** [TeamAOF/All-of-Fabric-6#170]
The version of Vinery in the pack is broken cant crush grapes to make the wine. The Mod has been updated to fix the problem but this pack does not have that current version.

**Comment by mtakemoto** [comment]
@Kinnickinick I was having this issue too, but I updated to v1.5.2 and it's working now.  
Vinery mod author says it's been fixed, too: https://www.curseforge.com/minecraft/mc-mods/lets-do-wine/issues/82
