### ISSUE TITLE
the end crashed

### ISSUE THREAD

**Issue by dwadaw999** [TeamAOF/All-of-Fabric-6#173]
going into the end still crashes the server help

**Comment by dwadaw999** [comment]
[crash-2023-04-01_05.40.22-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11128536/crash-2023-04-01_05.40.22-server.txt)

**Comment by four2day** [comment]
still getting this bug aswell

**Comment by jpenilla** [comment]
you can work around this by pre-generating a small radius with chunky before going to the end, it will stall at 0% for a while but once it starts progressing it's safe to go to the end
