### ISSUE TITLE
The Twilight Forest not compatible with CTM Refabricated

### ISSUE THREAD

**Issue by CristiBg** [TeamAOF/All-of-Fabric-6#177]
The castle door form The Twilight Forest is not compatible with CTM Refabricated making the game to crash when the castle door is placed, if a chunk already had castle door blocks in it before loading the world, that chunk will not render.

**Comment by ThatGravyBoat** [comment]
A crash log would be helpful

**Comment by CristiBg** [comment]
[crash-2023-04-03_17.53.38-client.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11139544/crash-2023-04-03_17.53.38-client.txt)
