### ISSUE TITLE
Blockus barrels are deprecated and should be hidden from REI

### ISSUE THREAD

**Issue by James103** [TeamAOF/All-of-Fabric-6#178]
As of Blockus 2.5.8, the barrels added by the mod have no recipe because they are deprecated. The barrels still work, but it is not guaranteed that they still work in future versions of the mod.

Original statement from the mod author: https://github.com/Brandcraf06/Blockus/issues/238#issuecomment-1256784018

One way to resolve this is to add the item IDs of all Blockus barrels to this list, which hides them from REI.
https://github.com/TeamAOF/All-of-Fabric-6/blob/622a536aef14159f4ea8ba9f2ce3040aa10811e4/kubejs/client_scripts/rei.js#L2

Recipes could be added to the Blockus barrels (at least temporarily), but doing so would conflict with the vanilla barrel unless the custom recipes for the Blockus barrels also cost 1 stick.

**Comment by fridayd** [comment]
As of 1.7.0, the blockus barrels are visible in REI. I _think_ they always have been, to my memory.

Other items included in that `DELETED_ITEMS` list are _not_ visible in REI.

**Comment by James103** [comment]
> As of 1.7.0, the blockus barrels are visible in REI. I _think_ they always have been, to my memory.

Can you please enable advanced tooltips (F3+H) and post screenshots of the tooltips (including the item ID) of the Blockus barrels which are visible but shouldn't be?

**Comment by fridayd** [comment]
Can do after work today.
They’ve always shown up searching for “barrel”, as I recall.

**Comment by fridayd** [comment]
Here is a screenshot with the tooltip showing for one Blockus barrel... more are clearly visible in the REI search results for "barrel".

![2023-06-26_09 28 41](https://github.com/TeamAOF/All-of-Fabric-6/assets/6677700/877de009-2d4a-4855-a19f-228c00bce7b5)
