### ISSUE TITLE
Unable to load AOF6 Due to "Mod Expandability" Issues. 

### ISSUE THREAD

**Issue by KillerSky05** [TeamAOF/All-of-Fabric-6#179]
I am unable to load into the game of All of Fabric 6 and it is telling me I have an issue with a mod expandability issue. I have over 80 GB free of memory. 
![image](https://user-images.githubusercontent.com/129762629/229649004-e9404333-ee3a-4b1c-b063-e374107113bc.png)

**Comment by James103** [comment]
Firstly, can you please post the full log?
Secondly, can you please try updating the mod with the ID 'expandability' to its latest version?
