### ISSUE TITLE
Leshon head Crashes

### ISSUE THREAD

**Issue by KachoGuerrero** [TeamAOF/All-of-Fabric-6#184]
There is currently an issue where if you try to Add an enchantment to a leshon head inside of an anvil it will cause the game client to immediately crash, 

If someone was todo this with an Auto Anvil or something of the like , it can potentially crash the server it was on. 

![image_2023-04-08_161642792](https://user-images.githubusercontent.com/33899255/230742871-66987992-b190-41d5-ad02-5b2bcd3e8ffb.png)

The game crashed whilst container click
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1856.method_8093(net.minecraft.class_1799)" because the return value of "net.minecraft.class_1741.method_7695()" is null

**Comment by James103** [comment]
Do you have the full crash report? If so, can you please post it here?

**Comment by KachoGuerrero** [comment]
[latest.log](https://github.com/TeamAOF/All-of-Fabric-6/files/11184323/latest.log)


> Do you have the full crash report? If so, can you please post it here?
