### ISSUE TITLE
FTB Ultimine creates invisible blocks when used with Modern Industrialization steam drill.

### ISSUE THREAD

**Issue by eggaroonie** [TeamAOF/All-of-Fabric-6#185]
Activating FTB Ultimine vein mining while using the Modern Industrialization steam drill will visually mine the entire highlighted area, but there will be invisible blocks with buggy collisions left over. It is occasionally possible to still mine these blocks, and FTB Ultimine will sometimes even continue to highlight them if they are hovered over with the '~' key pressed. This seems to be more common with larger veins/selections of blocks.

**Comment by James103** [comment]
The Steam Mining Drill mines in a 3x3 area by default, which overrides FTB Ultimine server-side.
Try crouching while ultimining, which reduces the mining area to a single block and should allow FTB Ultimine to work properly with the drill.
