### ISSUE TITLE
Server crashes shortly after the first player joins

### ISSUE THREAD

**Issue by jaydenhawkes123** [TeamAOF/All-of-Fabric-6#191]
Seems to happen when I join then walk around a bit, same with other plays, tried world on two different hosts / just took the world file accross, same issue. Crash report below
[crash-2023-04-12_16.31.59-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11207998/crash-2023-04-12_16.31.59-server.txt)

**Comment by mbrucher** [comment]
I have the same problem on 1.5.2, 1.5.1 is fine.
