### ISSUE TITLE
Create / Twilight Forest Recipe Issue

### ISSUE THREAD

**Issue by Stroobz** [TeamAOF/All-of-Fabric-6#195]
Greetings!

I'm trying to fix an issue with the recipe for oak logs and the create sawmill

The Create sawmill, take oak logs for example, will either create the stripped oak log or the hollow log from twilight forest.

I'm attempting to fix the recipe using kubejs.

We were able to fix a different issue with croptopia dough in this manner, which I'll leave here as a good faith gesture. 
event.replaceInput({}, 'croptopia:dough', '#c:dough' -- server scripts/replace_inputs.js

Thanks for reading!

**Comment by fridayd** [comment]
The create sawmill works best (ie: produces what you want reliably) when setting a filter on it, just as Create's basin does when performing mixing recipes.

Does your problem persist after setting a filter on the sawmill?
