### ISSUE TITLE
AE2 Formation planes not working in claimed chunks.

### ISSUE THREAD

**Issue by jeytee84** [TeamAOF/All-of-Fabric-6#197]
They do not place blocks in (FTBchunks) claimed chunks (as soon as unclaimed, they do). The annihilation planes do work.

**Comment by James103** [comment]
Try enabling the "Allow Fake Players" option in the settings for your team in FTB Teams. If you are not the owner of the team, ask the owner to do so.

**Comment by jeytee84** [comment]
Yup, that fixed it, thanks! Though it should be on by default isnt it? It was working fine without setting this in 1.5.1.

**Comment by dandin87** [comment]
This is a change made in FTB chunks. The downside of allowing fake players in claims by default is that someone could setup machines to siphon things from others claims. So we are hesitant to change that setting for the pack, and FTB chunks dev specifically mention that would probably not be ideal. They are trying to push other mod devs to assign players uuid to the fake player machines instead.

**Comment by jeytee84** [comment]
Clear, thank you. It might be a good idea then to put a new entry in the questbook about chunk claiming mentioning this, so new players would know what to do. Especially those, running singleplayer. The new certus growing mechanism in AE2 makes setting up an generator with planes pretty much essential now so new players (and the ones updating from 1.5.1) will probably run into the same issue.
