### ISSUE TITLE
Can't craft Silicon Cell with Tech Reborn

### ISSUE THREAD

**Issue by osiris-plus** [TeamAOF/All-of-Fabric-6#20]
Expected this Tech Reborn recipe to work but it does not function
https://github.com/TechReborn/TechReborn/blob/1.19/src/main/resources/data/techreborn/recipes/blast_furnace/silicon_cell.json

Silicon Cell is required to craft Silicon Plate. https://github.com/TechReborn/TechReborn/blob/1.19/src/main/resources/data/techreborn/recipes/blast_furnace/silicon_plate.json

This breaks progression in Tech Reborn, can't craft MFE. REI suggests to go with Modern Industrialization, which is not acceptable.

**Comment by ImAK9** [comment]
Fixed in 1.0.0
