### ISSUE TITLE
Recipe suggestion: Centrifuge 1000 mB of Thatch into 850 mB of Plant Oil

### ISSUE THREAD

**Issue by James103** [TeamAOF/All-of-Fabric-6#212]
Currently (AOF6 1.5.x), there is no use for Thatch except as decoration, which effectively makes it a dead-end in terms of wheat processing. Thatch can be stored as a fluid in any fluid container except vanilla buckets, but it has no uses.
Therefore, I would like to propose the following recipe:
* Machine: Centrifuge (Modern Industrialization)
* Energy cost: 8 EU/t for 10 seconds totalling 1600 EU
* Input: 1000 mB of Thatch
* Output: 850 mB of Plant Oil

The above recipe is identical to the one for centrifuging Hay Bales, just that the input is a fluid and not an item. The proposed recipe is useful for getting rid of excess Thatch (besides just using a vanilla bucket to remove/void the fluid in-world).

**Comment by James103** [comment]
I don't know the exact ID of the thatch used in the originally posted recipe, but if it contains the word `thatch`, as of AOF6 1.8.0, there still exists no custom recipe that I know of matching the specification in the original post.

**Comment by ImAK9** [comment]
Added in 1.8.1
