### ISSUE TITLE
Mod Suggestion -  OpenBlocks Elevator (Fabric)

### ISSUE THREAD

**Issue by farrucho** [TeamAOF/All-of-Fabric-6#220]
Simple port of the OpenBlocks Elevator mod to Fabric
This mod adds the famous 1.12.2 Elevator block, fully functional so you can teleport up and down in your world.
You can even edit the range of the blocks in the config.
I think this mod would be a good addition because in the old days of 1.12.2 everyone loved this elevator.

**Comment by DuroCodes** [comment]
kibe has elevators
