### ISSUE TITLE
Mod Suggestion - UnlimitedPeripheralWorks

### ISSUE THREAD

**Issue by SirEdvin** [TeamAOF/All-of-Fabric-6#221]
Adds a bunch of new possibilities for Computers from CC:R, shameless self promotion :)

Most noticeable:

- Provides support for fabric transfer api, so storages that don't implement Container, like ExtendedStorage chests are now usable
- Provides supports for fluid transfering
- Provides support for energy viewing inside energy storages
- Provides support for Modern industrialization machiens
- Provides support for AE2

CurseForge: https://www.curseforge.com/minecraft/mc-mods/unlimitedperipheralworks
Modrinth: https://modrinth.com/mod/unlimitedperipheralworks
Documentation: https://docs.siredvin.site/unlimitedperipheralworks/

**Comment by Lgmrszd** [comment]
This is a must, ComputerCraft doesn't do much on it's own, especially if you can't interact with other mod containers

**Comment by luo-zi** [comment]
I like it
