### ISSUE TITLE
Add Items to Replicator Blacklist

### ISSUE THREAD

**Issue by LiNoKami** [TeamAOF/All-of-Fabric-6#223]
Should add Magic Bags from Building Wands mod to the blacklist of the MI Replicator. 
I can copy the magic bag with content, which does not seem intended.
This way I can replicate several stacks of items with just 100mb of uu-matter and blacklisted items are no exception.

(Also works with AE2 Network tool lol)

**Comment by LiNoKami** [comment]
If anyone could also tell me where the blacklist is, I would be happy.

**Comment by 800020h** [comment]
the blacklist for the modpack is here
https://github.com/TeamAOF/All-of-Fabric-6/blob/main/kubejs/server_scripts/tags/replicator_blacklist.js
in your instance it would be `minecraft/kubejs/server_scripts/tags/replicator_blacklist.js`

**Comment by James103** [comment]
The part of this issue about Magic Bags not being in the MI replicator blacklist is fixed, but the AE2 Network Tool is also mentioned and is still not in the blacklist. I've split that part into a separate issue (#301) linked above.
https://github.com/TeamAOF/All-of-Fabric-6/blob/07b4f958104e0fedddb02dc99b7aea5719070ab0/kubejs/server_scripts/tags/replicator_blacklist.js#L225-L227
