### ISSUE TITLE
Server Crashing when going to the end 

### ISSUE THREAD

**Issue by 00Jayy** [TeamAOF/All-of-Fabric-6#229]
I've hosting and playing on a server and we've been having issues with trying to go to the end every time we step in the portal the server crashes is this common if so is there a fix?

**Comment by Teboran** [comment]
Getting the same problem.
[crash-2023-05-13_18.17.17-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11470768/crash-2023-05-13_18.17.17-server.txt)
