### ISSUE TITLE
[Suggestion] New ways of mining with FE

### ISSUE THREAD

**Issue by EvanZarrella** [TeamAOF/All-of-Fabric-6#234]
Probably for a future AOF version but I think that's something interesting to consider.

Given that Modern Industrialization is an ore dump (thousands of ingots for the later crafts, if not tens of thousands) I think this pack needs something allowing for AFK/offline ore generation with FE. 

The two main ways to generate Ore are MI's quarries which are 1) slow and 2) consumes a vast amount of resources and the drills from Industrial Revolution with the Ore Data Card. I believe that an intermediate solution, if it exists for Fabric, needs to be added. I my head, it takes the shape of MineFactory's Laser Drill but that's for the idea. 

The reasoning is that lots of basic processing and recipes have shortcuts through either Industrial Revolution or Tech Reborn, allowing using FE instead of EU. I do think of something really high tier in order to make use of that maxed Fusion Reactor from Tech Reborn and for balance.

For context, me and my friend set up the craft for MI's quantum upgrade and realized that in order to craft 1, we need around12k stainless steel which equate 1.4k manganese. Our ore processing is based on TR + IR which leads to only one way to produce manganese, Ruby. Now the numbers get stupid because **per quantum upgrade** 144k ruby ore are needed (10/11 ore card from IR). 

Such a mod may not exist for Fabric, but I think at least having the idea out there is important. The solution to our problem would be to rework ***all*** of our ore processing to MI but that, I believe, defeats the purpose of kitchen sink packs. 

I'd like to hear people's opinion about that but while playing, I really was like "I wish I had MineFactory's Laser Drill on hand".

Sorry for the wall of text, and huge thanks to the team providing this modpack to us. Having a blast playing it coop.

**Comment by Trent2087** [comment]
MI Electric Quarries when overclocked and upgraded to higher energy tiers are not slow, and the answer to before overclocking is to have more Quarries. And the resources it provides are more than enough to put back into auto assembling the drills, which results in a net gain. The Assembler is one of the most important MI machines. 

As for energy, MI can power everything else, but it purposefully does not accept energy from other mods so that you can't skip the steeam progression. There is a config option to change this though. The pack will not change it, but it is there.

**Comment by EvanZarrella** [comment]
I get the part of not skipping the steam age, on the other hand, I see a problem with having *tons* of ways to generate massive amount of FE (Powah for early game and midgame, TR Fusion Reactor for end game) but on the other hand being stuck to MI painfully slow progression. 

The same problem was in an old (like 1.4.7) version of Minecraft but blocs existed to convert from one type of energy to the other.  I wonder if something like that exists and if it would be welcomed in this pack (that may be a question for the MI team though). 

My point, in the end, is more that we have tons of ways to generate FE power and very little ways to use it. Not even an absurd way like "fill the max tier Draconic Evolution orb". Comparatively, every part of MI is a hassle that has little interaction with the other tech mods. I took mining as an example but in my opinion the issue lies in this fact.

**Comment by Linguardium** [comment]
MI has a config setting for it, that is intentionally not set to allow it. see enableBidirectionalEnergyCompat in the MI config
