### ISSUE TITLE
Lootbags contain nothing

### ISSUE THREAD

**Issue by MKcyborg** [TeamAOF/All-of-Fabric-6#235]
Whenever I open a loot bag (the ones given out by quests,) they don't seem to give me anything. I'm not sure if this is caused because I'm on a multiplayer server, but nothing new shows up in my inventory or is dropped on the ground.

**Comment by Trent2087** [comment]
You are most likely missing the /kubejs folder on your server. You can simply copy it from your client.

**Comment by MKcyborg** [comment]
I finally managed to get the owner of the server to check, and it seems the kubejs folder is there. Any other possibilities as to why I'm not getting anything from lootbags?
