### ISSUE TITLE
Shared recipies: Drying Rack and Item Shelf

### ISSUE THREAD

**Issue by MKcyborg** [TeamAOF/All-of-Fabric-6#236]
I noticed that the drying rack and the item shelf both seem to share the same recipe (three wood slabs in a horizontal line). I was trying to make the rack, but it only lets me make the shelf. Is there a way to choose what the recipe makes, or could it be a problem with the multiplayer server I'm on?

**Comment by ImAK9** [comment]
Update your pack, this was fixed a couple updates ago.
