### ISSUE TITLE
Server Crashing with BisectHosting 8GB

### ISSUE THREAD

**Issue by Azervyn** [TeamAOF/All-of-Fabric-6#237]
I had purchased a 6GB server for All of Fabric 6 and had multiple instances of crashing. I thought that the RAM was the issue so I upgraded to the 8GB server but the problem still persists. I am at a loss for what to do.  Any suggestions would be appreciated.

https://mclo.gs/nJaNTEM

Crash log is in the link.

**Comment by ZestyBlaze** [comment]
It's an issue with Lootr crashing with because MC locks up structure locating with maps, it's unfixable with Lootr but there is another mod that should be released soon that fixes it

**Comment by Nerdnub** [comment]
A temporary, but annoying, workaround for this is to set your server's max tick to a higher number than one minute (default: 60000ms). If you just add a zero to the end and make it 10 minutes, the server won't crash as a result of an extended tick time. Eventually, the server will spit out an empty "buried treasure map" and open the chest containing it, and the server won't crash. You'll just have a really huge lag spike in the meantime.
