### ISSUE TITLE
Server Crashes when we try to enter the End Portal

### ISSUE THREAD

**Issue by Gi11on** [TeamAOF/All-of-Fabric-6#238]
Every time we try to go into the End Portal we keep falling infinitely until the server times out and then it resets to the most recent auto-save.
[crash-2023-05-22_22.45.05-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11537579/crash-2023-05-22_22.45.05-server.txt)

**Comment by DaddyBigDonger** [comment]
Same problem for me too, it appears to be a problem generating "The End".

**Comment by zafyr51** [comment]
im having the same problem but also with the nether.
