### ISSUE TITLE
Text legibility issue with in game books

### ISSUE THREAD

**Issue by e-SonOfAnder** [TeamAOF/All-of-Fabric-6#239]
On the current version of the modpack (1.5.4 as of writing this), many of the in game guidebooks are unreadable, I have added no other mods, datapacks, or resource packs to the installation.

Attaching a screenshot showing an example of the issue:
![aof6 book text](https://github.com/TeamAOF/All-of-Fabric-6/assets/4420108/ccbaa657-eb4f-497e-99fe-70c72327006b)

**Comment by Trent2087** [comment]
If single player, remove emojiful. Since it still hasn't been addressed will likely be removed next update.
See https://github.com/InnovativeOnlineIndustries/Emojiful/issues/78
