### ISSUE TITLE
Loot Chests Spawning instead of AE2 Mysterious Cubes

### ISSUE THREAD

**Issue by alfieengland** [TeamAOF/All-of-Fabric-6#24]
Loot chests are in the center of AE2 Meteorites instead of Mysterious Cubes, the loot chests do not contain any AE2 patterns.

**Comment by ImAK9** [comment]
You sure it ain’t a Ad Astra meteorite?

**Comment by alfieengland** [comment]
Ah possibly, but as they contained Sky Stone I thought they would be AE2
