### ISSUE TITLE
New issue with Vinery - Apple Juice... is broken.

### ISSUE THREAD

**Issue by MommaDragon** [TeamAOF/All-of-Fabric-6#241]
Older version Apple Juice don't stack with New Version (or some other weird setup might trigger this effect), but what's weirder is that *all* Apple Juice she has made or had now all produce bottles but are not consumed.

No idea how to display the difference, if not to show Advanced Tooltips.
Fresh bottles
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/106483611/2bd93e68-3d9e-4ca1-9673-2204593207f2)
Old bottles
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/106483611/98092d8c-49bb-4c25-9640-121710db8967)
And what's still in the barrel.
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/106483611/eb2a33e0-df26-4e36-a888-53f336c310c5)

Note the lack of (visible) differences. It might not even be in the log...

**Comment by ImAK9** [comment]
Fixed in 1.6.1
