### ISSUE TITLE
1.6.0 - Wheat Dough recipe missing - Farmers Delight 

### ISSUE THREAD

**Issue by KuroxLemming** [TeamAOF/All-of-Fabric-6#242]
![2023-05-26 23_05_18-Window](https://github.com/TeamAOF/All-of-Fabric-6/assets/107375891/4c9dbe44-f65e-470f-8013-8cf13cdc7ec2)

The recipe for it worked in 1.5.9 but when updating to 1.6.0 it vanished can't even use the old way to make it and any recipe that needed it can't be crafted now.

![2023-05-26 23_11_11-All of Fabric 6 - 1 19 2](https://github.com/TeamAOF/All-of-Fabric-6/assets/107375891/bb1dd97e-1e58-4f13-a585-6676e93174f1)

**Comment by ImAK9** [comment]
Fixed in 1.6.1
