### ISSUE TITLE
[Bug] 1.6.0 - Can't Craft ReChiseled's Chisel

### ISSUE THREAD

**Issue by Ant-Redstone** [TeamAOF/All-of-Fabric-6#243]
ReChiseled's Chisel has the same recipe as Iron Sai from Simply Swords

![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/32925592/c119debd-3a19-4f70-bf61-279f86680f5e)

**Comment by ImAK9** [comment]
Fixed in 1.6.1
