### ISSUE TITLE
Simeball recipe (Create's dough + lime dye) is broken

### ISSUE THREAD

**Issue by fridayd** [TeamAOF/All-of-Fabric-6#245]
- Recipe will show up in REI, but the dough will be missing in the illustration.
- Reverse searching REI from the dough will not show the slime recipe.
- Recipe does not work if dough and lime dye is put in a Create mixer.

Tested in 1.6.1

**Comment by Kazuhiko-Gushiken** [comment]
I've found a fix. `@Keno#0316` here. I've found that in previous versions of AoF6 (in this case I tested a 1.4.3 version profile I had already made) that in the unification file in the KubeJS server scripts, it had `event.add('c:doughs', 'vinery:dough')`. Now, in 1.6.1, the unification file has *both* `event.add('c:doughs', 'vinery:dough')` *and* `event.add('c:doughs', 'create:dough')`. It seems it gets confused setting both types of dough to be in the same location, so it wipes the entire dough from seemingly that single recipe. Removing the `event.add('c:doughs', 'vinery:dough')` and keeping *only* the `event.add('c:doughs', 'create:dough')` seems to fix the slimeball recipe. I have not done further testing or cross checked other recipes it might have broken. I can try to check, but no promises.
