### ISSUE TITLE
Registry remapping failed

### ISSUE THREAD

**Issue by Hyzteria-xL** [TeamAOF/All-of-Fabric-6#246]
Trying to join my GF's server and i'm getting a registry remapping failed where it says it is receiving IDs unknown to the receiver involving vinery:old cherry wood, vinery:tomato crop, and other vinery IDs. I have the most up to date pack from curse forge and so does she. Yet i am the only one of our friends that cant play on the server. A quick note shows that her server has access to these items but if I play solo in my own world I do not.

**Comment by Trent2087** [comment]
You are on a different version then the server. What pack version are they on? Its in the lower left of the title screen.

**Comment by Hyzteria-xL** [comment]
> You are on a different version then the server. What pack version are they on? Its in the lower left of the title screen.

that'd be why.. I'm on 1.6.1 and they are on 1.5.4

**Comment by Hyzteria-xL** [comment]
> You are on a different version then the server. What pack version are they on? Its in the lower left of the title screen.

we updated the server.. both versions are matching and im still having the issue
