### ISSUE TITLE
Major REI or Questing Softlock

### ISSUE THREAD

**Issue by badlandsrise** [TeamAOF/All-of-Fabric-6#247]
Occasionally when switching from REI crafting recipes to the quest book or vice versa, you end up trapped in a loop between the two. Pressing escape or E simply switches you back to the other rather than closing either. I can't recreate it manually, but it happens very very frequently and requires the game to be closed without saving to fix.

**Comment by Zach918** [comment]
If you run into this alt-tabbing crashed my game, but it saved my 26 minutes worth of crafting

**Comment by libjared** [comment]
Workaround: In REI, navigate to a recipe you can craft with your current inventory (like planks to sticks) and click the plus button, and it should take you out of the loop.

**Comment by Zach918** [comment]
> Workaround: In REI, navigate to a recipe you can craft with your current inventory (like planks to sticks) and click the plus button, and it should take you out of the loop.

MUCH love to you.

**Comment by fr4mes** [comment]
I found that if you click the ftb chunks map and then escape as normal, it lets you out of the loop
