### ISSUE TITLE
[v1.6.1] Farmers Delight cutting board recipes only accept vanilla tools

### ISSUE THREAD

**Issue by Gronglegrowth** [TeamAOF/All-of-Fabric-6#250]
None of the tool tags on the farmers delight cutting board recipes are populated with their corresponding modded tools, thus for all except shears, only the vanilla tool materials are able to be used in recipes with this block

**Comment by Gronglegrowth** [comment]
Clarification: seems the cutting board is using a Different tag convention than just about everything else, maybe to fix this consider changing the cutting board's recipes to refer to, for example, `c:axes` instead of `c:tools/axe` (I think that's what it was using)

**Comment by DaFuqs** [comment]
Reported here: https://github.com/newhoryzon/farmers-delight-fabric/issues/135
