### ISSUE TITLE
[Dupe] Chromium Dust -> Chromium Tiny Dust -> Chromium Dust = more Chromium Dust

### ISSUE THREAD

**Issue by llloyd4** [TeamAOF/All-of-Fabric-6#253]
If you convert Chromium Dust to Chromium Tiny Dust you get 9 Chromium Tiny Dust, if you then use 4 Chromium Tiny Dust in a Crafting Grid you get one Chromium Dust. So for one Chromium Dust you can get 2 plus 1 extra Chromium Tiny Dust. Posted it over on the Modern Industrialization Discord and was sent here. So...

https://i.imgur.com/KHLg3Sd.png
https://i.imgur.com/1V9UxNw.png

**Comment by fridayd** [comment]
This report, though earnest, was made in error. OP was playing an outdated AoF6 release; confirmed in chat with them.
