### ISSUE TITLE
Traveller's Backpack bonus effects not working

### ISSUE THREAD

**Issue by MKcyborg** [TeamAOF/All-of-Fabric-6#255]
It seems that the side effects of the traveller's backpacks aren't working. I tested this out with the lava cube (immune to fire damage) and the pumpkin ones (Endermen don't go aggro when stared at) but the special effects didn't seem to trigger

**Comment by Linguardium** [comment]
did you toggle the special effect on in the traveler backpack? they are off when you craft them and must be toggled on

**Comment by MKcyborg** [comment]
Ah, that would do it. I didn't know you had to turn them on, thanks
