### ISSUE TITLE
Industrial Revolution + Wireless Charger = Crash

### ISSUE THREAD

**Issue by SwissLuckyFox** [TeamAOF/All-of-Fabric-6#257]
Hello, I have a problem with my world crashing when I try to use a Wireless charger. I don't know exactly what causes it. It seems like if you put down multiple in a short amount of time, it crashes sometimes. I don't know if pattern provider are the cause as well.

Client Error:
`The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Parameter specified as non-null is null: method me.steven.indrev.registry.MachineRegistry$defaultEnergyProvider$1$1.invoke, parameter side`

Crash Reports:
Server:
[crash-2023-06-16_12.43.31-client.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11770570/crash-2023-06-16_12.43.31-client.txt)
Client:
[crash-2023-06-16_12.43.31-client.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11770603/crash-2023-06-16_12.43.31-client.txt)

Single-player World where I recreated the Crash:
[Wireless Crash.zip](https://github.com/TeamAOF/All-of-Fabric-6/files/11770572/Wireless.Crash.zip)

**Comment by Duskofdawn** [comment]
That's Industrial Revolution, not Tech Reborn. Here's the other two serverside crash reports.
[crash-2023-06-14_23.23.04-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11770636/crash-2023-06-14_23.23.04-server.txt)
[crash-2023-06-16_13.09.40-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11770637/crash-2023-06-16_13.09.40-server.txt)

**Comment by Lgmrszd** [comment]
Related issues:
https://github.com/SuperMartijn642/WirelessChargers/issues/20
https://github.com/GabrielOlvH/Industrial-Revolution/issues/537
Seems to be a problem with Wireless Chargers mod, as it attempts to charge blocks on client

**Comment by SwissLuckyFox** [comment]
Edit *its Industrial Revolution not Tech Reborn*

**Comment by Linguardium** [comment]
should be fixed in 1.7.0

**Comment by SwissLuckyFox** [comment]
> should be fixed in 1.7.0

Thanks!
