### ISSUE TITLE
Vinery Cooking Pot removed breaking agriculturist loot bag loot table

### ISSUE THREAD

**Issue by Linguardium** [TeamAOF/All-of-Fabric-6#259]
https://github.com/TeamAOF/All-of-Fabric-6/blob/0558b505f67673d05f416818cfb047509c5d9673/kubejs/data/aof/loot_tables/loot_bags/agriculturist_loot.json#L614

https://www.curseforge.com/minecraft/mc-mods/lets-do-wine/files/4582493 changelog for 1.3.0 breaking changes

**Comment by spokrr** [comment]
+1
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/69011306/8bded726-6c4f-40bd-8994-711a71309d31)

**Comment by ImAK9** [comment]
I’ll have this fixed with an update tomorrow
