### ISSUE TITLE
Botany Pots Inquiry

### ISSUE THREAD

**Issue by Vennexus** [TeamAOF/All-of-Fabric-6#26]
I would like to ask if it is possible to have Croptopia trees to be able to grow in botany pots, as their seeds are able to be placed in.

Twilight Forest and Minecraft's trees are also able to be planted in botany pots.

**Comment by Clonephaze** [comment]
This felt like it should be a feature of the Croptopia mod itself to me, so I opened an issue on their page for this. https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/475

**Comment by Clonephaze** [comment]
Looks like the mod author will be adding that support in natively to croptopia
