### ISSUE TITLE
AoF6 v1.7.0 The Quest "Awakening Rituals" has the wrong block gathering tasks.

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [TeamAOF/All-of-Fabric-6#260]
Currently it asks for:

1x Awakening Altar
8x Awakening Pedestals

The setup only requires:

1x Awakening Altar
4x Awakening Pedestals
4xEssence Vessels

- @officialkeno

**Comment by ImAK9** [comment]
Fixed in next update, thanks for reporting!
