### ISSUE TITLE
The following ores should be added to Industrial Revolution's Mining Rig whitelist.

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [TeamAOF/All-of-Fabric-6#261]
`mysticalagriculture:prosperity_ore`
`mysticalagriculture:deepslate_prosperity_ore`
`mysticalagriculture:inferium_ore`
`mysticalagriculture:deepslate_inferium_ore`
`mysticalagriculture:soulium_ore`

- @officialkeno

**Comment by ImAK9** [comment]
Added in next update!

**Comment by ImAK9** [comment]
Added in 1.7.1
