### ISSUE TITLE
Crash on sending item in message after deleting item

### ISSUE THREAD

**Issue by SHARDcoder** [TeamAOF/All-of-Fabric-6#268]
Using `ctrl+t` sends a message in chat prefixed with the item selected in inventory
Removing this initial part of the message, then attempting to chat in the same box causes a crash on send

Version 1.7.0

Repro steps:
`ctrl+t` item to add it to a chat message
Delete contents of message (both `ctrl+a` and backspace work)
Type new message
Send

Expected:
Message sends as a normal chat message

Actual:
Game crashes
Crash report [here](https://github.com/TeamAOF/All-of-Fabric-6/files/11793819/crash-2023-06-19_23.52.54-client.txt)

**Comment by libjared** [comment]
This is an issue in the mod _Show Me What You Got_: https://github.com/apace100/show-me-what-you-got/issues/6

I wrote and sent in a potential fix for this, so we're just waiting for it to be approved by the maintainer.

**Comment by libjared** [comment]
This is still an issue in 1.8.2. Please reopen.
