### ISSUE TITLE
Impossible to get the "Small Beginnings" Advancement from Tech Reborn

### ISSUE THREAD

**Issue by ShadedPL** [TeamAOF/All-of-Fabric-6#27]
As the title implies you are unable to get the "Small Beginnings" Advancement from Tech Reborn when taking out a Nickel Nugget from the Tech Reborn Centrifuge. Most likely because it's making the Nickel Nugget from Modern Industrialization.
![image](https://user-images.githubusercontent.com/4216212/205065546-83b7d3ad-06b9-456f-8bc9-3ffa3e4c018d.png)

I checked our Discord history if anyone got this achievement but no.

I know this is just an Advancement but for a completionist this is unacceptable :D

Cheers guys, and thanks for the work you put into this Pack!

**Comment by Clonephaze** [comment]
Can confirm. Even cheating in the nugget from tech reborn is all it takes to give that advancement; it's definitely an issue with it being from the wrong mod.

**Comment by Clonephaze** [comment]
None that I can see from tech reborn, haven't branched the other tech mods yet for testing. Most of tech reborns advancements are "craft" or "place". Other than rubber, which isn't an issue, there are no other advancements that require picking up.

**Comment by ImAK9** [comment]
The advancement should be using tags.

**Comment by Clonephaze** [comment]
Yeah but tech reborns nugget has the tags "#techreborn:nuggets" and "#c:nickel_nugget". Whereas MI's just has "#c:nickel_nugget".
