### ISSUE TITLE
How do I start a server on oracle cloud

### ISSUE THREAD

**Issue by imlostinzerogravity** [TeamAOF/All-of-Fabric-6#271]
Please all I see in the server pack is 4 files

**Comment by imlostinzerogravity** [comment]
i mean like oracle cloud the cloud server service by oracle

**Comment by Trent2087** [comment]
You need to unzip the files locally and run the .bat or .sh file. Then copy everything over

**Comment by imlostinzerogravity** [comment]
ok thanks!
