### ISSUE TITLE
[1.7.1] Awkward rendering of Create goggles

### ISSUE THREAD

**Issue by Gronglegrowth** [TeamAOF/All-of-Fabric-6#272]
The goggles from Create [render really weirdly](https://media.discordapp.net/attachments/801591103375015957/1121228540508115004/Screenshot_20230621_200151.png) when equipped, both in the helmet and in the face slot.

**Comment by fridayd** [comment]
Can confirm:

![2023-06-26_09 36 02](https://github.com/TeamAOF/All-of-Fabric-6/assets/6677700/68c35278-9baa-46d1-9270-28b7aa156203)
