### ISSUE TITLE
Error start server Ubuntu

### ISSUE THREAD

**Issue by GuAugLop** [TeamAOF/All-of-Fabric-6#278]
java -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu120.04, mixed mode, sharing)

Latest Log: https://github.com/GuAugLop/logs/blob/master/latest.log

Flow:
- wget https://mediafilez.forgecdn.net/files/4597/291/All-of-Fabric-6-Server-1.7.1.zip
- unzip
- running startserver.sh
- errors and freeze

**Comment by Linguardium** [comment]
does not appear to have an issue in the log. the errors you see are "normal" for this pack and there is an issue opened up to try to get the individual mods to fix their mods. they dont cause any actual issues.
