### ISSUE TITLE
Client Crash when entangle a Cable from Modern Industrialisation

### ISSUE THREAD

**Issue by SwissLuckyFox** [TeamAOF/All-of-Fabric-6#283]
The Client Crashes when you try to entangle a cable from Modern Industrialization. I tested it in single player with a cupronickel cable.

[crash-2023-07-03_07.54.53-client.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/11933751/crash-2023-07-03_07.54.53-client.txt)

**Comment by Kazuhiko-Gushiken** [comment]
Yeah, it crashes when you entangled *any* cable or *any* pipe from MI. You'll need to somehow remove the pipe/block without rendering those chunks to continue to play.
