### ISSUE TITLE
[suggestion] Update Create Fabric to 0.5.1

### ISSUE THREAD

**Issue by jjs98** [TeamAOF/All-of-Fabric-6#288]
It would be cool to have the [new create version](https://legacy.curseforge.com/minecraft/mc-mods/create-fabric/files/all?filter-game-version=1738749986%3a73407) in this modpack.
It adds a new water wheel type and also new elevator mechanics which are awesome.

Are there any plans on updating this?

**Comment by imstupidwithlinux** [comment]
ive tried installing it myself but i had no luck, have you tried it by any chance?

**Comment by ImAK9** [comment]
It’ll be added as soon as CC: Bridge and Crafts & Additions has been updated for new Create.

**Comment by 1Turtle** [comment]
CC:C Bridge dev here, I will update the mod within about this weekend. 1.19 is done, I have to port it back to 1.18 however. If the Backport is done I will release it. Shouldn't take too long.
