### ISSUE TITLE
[Suggestion] Add chipped support to AE2 Patterns

### ISSUE THREAD

**Issue by Icecreep109** [TeamAOF/All-of-Fabric-6#293]
AE2 has the ability to create stonecutting patterns to automate mass creation of chiseled blocks.  Chipped adds hundreds of new chiseled block variants, but isn't supported by AE2 stonecutting patterns.  Adding compatibility between the two (possibly via a KubeJS script) would make projects requiring large amounts of these chiseled blocks much easier.

**Comment by Trent2087** [comment]
You know, I did this on our servers and though we had added it to the pack. let me fix that :)
