### ISSUE TITLE
Botany pot missing

### ISSUE THREAD

**Issue by DloobyOwl** [TeamAOF/All-of-Fabric-6#300]
Why remove such a beatiful mod? it's remove the most horrible and boring part of modern industrialization and other tech mod. why not add some config to remove the crafting of botany pot and not simply remove the entire mod??

**Comment by Linguardium** [comment]
https://github.com/TeamAOF/All-of-Fabric-6/blob/07b4f958104e0fedddb02dc99b7aea5719070ab0/changelogs/CHANGELOG.md?plain=1#L16-L17

significant lag and tps issues. a custom structure was added to take its place in the electric age of MI

Look into villager trades if you want to speed up the early boring part. They offer surprisingly good trades

**Comment by ImAK9** [comment]
botany pots wont be added back.
