### ISSUE TITLE
AE2 network tool needs to be added to the Replicator blacklist

### ISSUE THREAD

**Issue by James103** [TeamAOF/All-of-Fabric-6#301]
The AE2 Network Tool can hold items within, but the MI Replicator should not be able to duplicate items that can directly hold other items. Therefore, the AE2 Network Tool should be added to the MI Replicator blacklist here: https://github.com/TeamAOF/All-of-Fabric-6/blob/main/kubejs/server_scripts/tags/replicator_blacklist.js

Similar to https://github.com/TeamAOF/All-of-Fabric-6/issues/223, but that issue also concerns the Magic Bags from Building Wands, which is fixed.

**Comment by ImAK9** [comment]
Added in 1.8.1
