### ISSUE TITLE
Downloading server pack?

### ISSUE THREAD

**Issue by Sh1tL0rd** [TeamAOF/All-of-Fabric-6#306]
cant download server pack

Not every host could be reached?
![Screenshot 2023-07-12 203223](https://github.com/TeamAOF/All-of-Fabric-6/assets/139343544/024f2e63-24c6-4e9d-b373-9b75f3610530)
there's nothing wrong with my internet connection, I've tested with different computers on different networks and none can ping example.com
this has been driving me insane I don't know where else to get help for this issue?

**Comment by Linguardium** [comment]
your internet service provider is having issues. you can disable the check in the yaml config file

**Comment by Sh1tL0rd** [comment]
Thankyou!

**Comment by Sh1tL0rd** [comment]
sorry to reopen, cant find where to disable the check in any of the config files

**Comment by Linguardium** [comment]
open server-startup-config.yaml in a text editor

change `  checkOffline: true` to `  checkOffline: false`

**Comment by Sh1tL0rd** [comment]
thankyou idk how i missed that :(
