### ISSUE TITLE
Spectrum book and shrine crashes.

### ISSUE THREAD

**Issue by JasonBlunder** [TeamAOF/All-of-Fabric-6#308]
There is a recent bug report in the spectrum mod 
link: https://github.com/DaFuqs/Spectrum/issues/206 

Unless it is a fresh install using the shrine causes a client side crash. DaFugs stated they are working on a Band-aid fix for the conflict, also in link. The book for the spectrum mod also shows a loading error involving the shrine causing it to also stop working. The quest book however still works involving the Spectrum mod.

**Comment by ImAK9** [comment]
Fixed in 1.8.2
