### ISSUE TITLE
Coal Dust -> Carbon Dust not available in tech reborn Indurstrial Centrifuge

### ISSUE THREAD

**Issue by osiris-plus** [TeamAOF/All-of-Fabric-6#31]
Coal Dust -> Carbon Dust not available in tech reborn Indurstrial Centrifuge

**Comment by ShadedPL** [comment]
Yeah, can confirm, putting coal dust into the machine as per recipe and nothing happens
![image](https://user-images.githubusercontent.com/4216212/205581277-d4b9edf3-b340-48ab-b6ea-37c4c4069353.png)
