### ISSUE TITLE
Botany Pots

### ISSUE THREAD

**Issue by Harrrussy** [TeamAOF/All-of-Fabric-6#318]
All of my flipping Botany Pots disappeared, with all of my seeds and Supremium farmland. 

This is NOT flipping cool.

**Comment by spokrr** [comment]
update notes are your friend

**Comment by libjared** [comment]
A Major version bump would have been nice, since it is a breaking change.

**Comment by Linguardium** [comment]
it did not fundementally change the focus and structure of the pack, so i dont think a major change is necessary. it _did_ go from 1.7.1 to 1.8.0 so that should have clued you in, if versions were going to do it, that there was a large scale change

**Comment by libjared** [comment]
Focus and structure are not what semver measures. Version bumps
differentiate between
(a) breaking changes, (b) backward-compatible feature changes, and (c)
backward-compatible bug fixes. The size of the update is irrelevant.

As the removal of botany pots breaks all existing factories that make use
of them, it is a breaking change. Don't you agree?

The only thing going forward that I would like to see is that version
numbers more accurately reflect the compatibility of the changes within.
Thanks for listening.

**Comment by Trent2087** [comment]
Well we just try and do what Mojang does. They break world gen between in .1 versions... so....

**Comment by Linguardium** [comment]
I would say that the semver versioning is referring to public APIs not to application functionality.  The only thing similar to an api in this case would be the documented "usage" of the modpack, which would be the questline. 

The current questline is backwards compatible and did not break between versions so the semver backwards compatibility is maintained. There were "undocumented/experimental" features of the api that you seem to have been relying on, and changes affecting those "experimental" features are documented in release notes.
