### ISSUE TITLE
MI Texture change

### ISSUE THREAD

**Issue by Tekator99** [TeamAOF/All-of-Fabric-6#319]
I like the new textures for MI, but I am confused by the whole new look. Could you please tell me where the .png files with the new textures are, so I can change them manually? Or could you tell me how I can change them back?  Thank you in advance! :D

**Comment by Linguardium** [comment]
kubejs\assets\modern_industrialization\textures

**Comment by Tekator99** [comment]
Okay, I tried changing the textures by hand, but because there are now such files as "machine_overlay_left" and new scripts, I can't seem to change everything to its original state. since some machines did not have any animations on their sides originally. 
In addition to that, all of the multiblocks are still unchanged after my attempts of changing the textures. 
I'd be very grateful if you could help me there.

I would suggest a sort of ressource/texture pack with legacy textures if that's possible. :D

**Comment by Linguardium** [comment]
If you back up 1 folder to kubejs\assets\modern_industrialization\ you can access the new models and stuff. 

I would also like to see it released as a resource pack rather than a kubejs config. that way users can disable it manually if desired

**Comment by ImAK9** [comment]
A resourcepack is planned
