### ISSUE TITLE
[AE2] Formation Plane is not placing blocks but just dropping items

### ISSUE THREAD

**Issue by abnercbalmeida** [TeamAOF/All-of-Fabric-6#324]
Hi, I've been trying to setup a system that places blocks.
In order to be easier to reproduce, I followed this formation plane setup: [YouTube](https://youtu.be/2j6TWHJ4MoQ?t=2255)
In single player this works fine, but when I try the same in a server (this one is hosted on web), the block placement mode doesn't work, **just the dropping item mode.**

I'm using AOF 1.7.1, I checked in the changelogs of the latest versions and **there is no updates for AE2**.

**Comment by 800020h** [comment]
is it in a claim?
did you enable fake players in the claim?

**Comment by abnercbalmeida** [comment]
@800020h
**THAT'S IT!**
Thank you very much!
I would never think of that.
