### ISSUE TITLE
Game crash: Neutron generated without fuel

### ISSUE THREAD

**Issue by Urthelion** [TeamAOF/All-of-Fabric-6#327]
Game keeps crashing after a while. Got this crash 4 times today. I'll try to change the setup since I changed a few things, however I had a similar setup before I updated the modpack to 1.9 and didn't have this problem

[crash-2023-07-25_02.11.11-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/12158079/crash-2023-07-25_02.11.11-server.txt)

**Comment by Trent2087** [comment]
MI dev is now aware of the issue. For now you can downgrade MI to the previous version.

**Comment by Urthelion** [comment]
thank you for the quick response

**Comment by ImAK9** [comment]
1.9.1 should be out in a minute or two, fixing this
