### ISSUE TITLE
Can't throw/use some throwable weapons

### ISSUE THREAD

**Issue by Urthelion** [TeamAOF/All-of-Fabric-6#338]
When trying to throw weapons like a Trident by right clicking they just "blink" like trying to be used/charged but never do

I noticed this problem before in version 1.7 of the modpack with the bewitchment spear but I thought maybe I was missing something about the mod and stopped trying, however since the addition of the Marium's weapons I noticed this happening with some of them as well. I didnt change the key binds for Use Item

Video example attached:

https://github.com/TeamAOF/All-of-Fabric-6/assets/15002397/6ae1087a-d5e0-4a6c-8694-11ff6561ab01

**Comment by spokrr** [comment]
are you on 1.9.0 or 1.9.1?

**Comment by Urthelion** [comment]
oh forgot that, sorry. it's 1.9.0

**Comment by spokrr** [comment]
twas fixed in 1.9.1 i believe, try the update

**Comment by Urthelion** [comment]
oooh didn't notice there was a new version! Thank you

**Comment by Urthelion** [comment]
it is working now, thank you for the help

**Comment by spokrr** [comment]
np, consider closing the issue :)
