### ISSUE TITLE
Error in server console

### ISSUE THREAD

**Issue by Lucas-S-Vieira** [TeamAOF/All-of-Fabric-6#384]
I've created a server with my friends and im hosting in my machine, im using the version of the modpack (1.8.2).
in my console has this message, all the time: 
[09:06:21] [Netty Server IO #4/ERROR]: Twilight Forest: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null

My server doesnt close, but this message keep appearing

Edit: heres a print of the console
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/116003800/62764cf9-e05d-425c-9113-2bec9dd7d8f1)

**Comment by Linguardium** [comment]
try setting debugPrintMessages to true in connectivity's config file, this should flood the log a bit more. once it gives one of those timeout exceptions, post the log to mclo.gs again and post the link here. that may give more info as to whats going on.

**Comment by Lucas-S-Vieira** [comment]
Im running the server right now, but unitl the server open, is there any chance, that maybe this error is being caused because of my java JDK version?
Im using the official java jdk 17

**Comment by Lucas-S-Vieira** [comment]
The server is running right now, here is the log:
https://mclo.gs/nmgrFe4

**Comment by Linguardium** [comment]
> Im running the server right now, but unitl the server open, is there any chance, that maybe this error is being caused because of my java JDK version? Im using the official java jdk 17

No. Java 17 is supported. The error you are seeing is a timeout when attempting to communicate over the network. 

this appears like it may be caused by no-chat-reports

**Comment by Lucas-S-Vieira** [comment]
> > Im running the server right now, but unitl the server open, is there any chance, that maybe this error is being caused because of my java JDK version? Im using the official java jdk 17
> 
> No. Java 17 is supported. The error you are seeing is a timeout when attempting to communicate over the network.
> 
> this appears like it may be caused by no-chat-reports

What I can do to stop this error? just ignore it? or remove no-chat-reports?

**Comment by Lucas-S-Vieira** [comment]
i've saved the world and re-installed the rest of the modpack, and now its getting this log
https://mclo.gs/oXtyl5D

**Comment by Linguardium** [comment]
you seem to have something interfering with your network. Is this your local computer or a hosted server somewhere?

**Comment by Lucas-S-Vieira** [comment]
> you seem to have something interfering with your network. Is this your local computer or a hosted server somewhere?

Local computer

**Comment by Lucas-S-Vieira** [comment]
> you seem to have something interfering with your network. Is this your local computer or a hosted server somewhere?

but i didnt get it, why is a network problem?

**Comment by Linguardium** [comment]
> io.netty.handler.codec.DecoderException: java.io.IOException: Packet -1/0 (class_2889) was larger than I expected, found 48 bytes extra whilst reading packet 0

This says basically that the packet is malformed. packets are how things send data over the network

> io.netty.handler.codec.CorruptedFrameException: length wider than 21-bit

more packet corruption issues

> Caused by: java.lang.IndexOutOfBoundsException: Index 50 out of bounds for length 1

this one too

> io.netty.handler.timeout.ReadTimeoutException: null

this one isnt packet corruption but the game expecting to receive more data and it just not coming in, which also indicates a network problem

**Comment by Lucas-S-Vieira** [comment]
> > io.netty.handler.codec.DecoderException: java.io.IOException: Packet -1/0 (class_2889) was larger than I expected, found 48 bytes extra whilst reading packet 0
> 
> This says basically that the packet is malformed. packets are how things send data over the network
> 
> > io.netty.handler.codec.CorruptedFrameException: length wider than 21-bit
> 
> more packet corruption issues
> 
> > Caused by: java.lang.IndexOutOfBoundsException: Index 50 out of bounds for length 1
> 
> this one too
> 
> > io.netty.handler.timeout.ReadTimeoutException: null
> 
> this one isnt packet corruption but the game expecting to receive more data and it just not coming in, which also indicates a network problem

Have any hint of how can i solve this?

**Comment by Linguardium** [comment]
I would take a look at anything that might interfere. If you are using a vpn, test without it.. if you are using something like hamachi, disable it and test again, etc.
