### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Lucas-S-Vieira** [TeamAOF/All-of-Fabric-6#386]
logs: https://mclo.gs/Fs8YIgM
We and my friends were playing normaly, and now our server just dont stop open, and we dont know why

Crash report: 
[crash-2023-09-18_19.49.36-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/12654061/crash-2023-09-18_19.49.36-server.txt)

**Comment by Linguardium** [comment]
someone left a farm running in the nether and it is lagging out the server; there are 7800 items floating around in there. turn off the watchdog by setting the max-tick-time to -1 or delete those entities by editing the files.

**Comment by Lucas-S-Vieira** [comment]
Thanks
