### ISSUE TITLE
Large and small waterwheels are always a gross green colour.

### ISSUE THREAD

**Issue by Deadpickle872** [TeamAOF/All-of-Fabric-6#412]
As the title says, for some reason the create waterwheels are always some shade of green no matter what type of wood I apply to them
![Water wheel issue](https://github.com/user-attachments/assets/3d952f28-66bc-4e7b-87c9-16b2fdef2861)

**Comment by Linguardium** [comment]
normally this occurs with debug mode active. did you turn on any debug settings with flywheel?

**Comment by Deadpickle872** [comment]
I certainly don't recall doing anything with debug, if that is the case how to i turn off debug mode?

**Comment by Deadpickle872** [comment]
![debug mode](https://github.com/user-attachments/assets/abe32656-1752-46a4-aafb-f16b7fcd854f)
so I played with the flywheel debug, this is what it looks like with debug on.

**Comment by Deadpickle872** [comment]
I fixed it, turned backend off. no idea why that was changed. sorry for issue creation lol.
