### ISSUE TITLE
Unable to join after upgrading to 1.2.0

### ISSUE THREAD

**Issue by xorinzor** [TeamAOF/All-of-Fabric-6#50]
![image](https://user-images.githubusercontent.com/4212335/210177776-ad524f1e-e64c-4bf8-a384-34e5502ce805.png)

After updating from the previous version to 1.2.0 the server gives this error upon joining.

```
Registry remapping failed: Received ID map for minecraft:item contains IDs unknown to the receiver!
- srias_flowers:blue_poppy
- srias_flowers:hydrangae
- srias_flowers:orange_daisy
- srias_flowers:umbrella_leaf
- srias_flowers:crocus
```

**Comment by Linguardium** [comment]
official servers are on 1.1.1, so this would be expected

**Comment by xorinzor** [comment]
This is not an official server, this is my private server

**Comment by Linguardium** [comment]
did both client and server update to 1.2.0 and are the configs all the same? this is saying there are flowers on the server but not the client

**Comment by xorinzor** [comment]
Turns out that the docker container isn't smart enough to update the modpack with the new zip once the environment variable was changed. Will do a manual upgrade; I assume that'll fix the issue.

**Comment by xorinzor** [comment]
Just to confirm, the server was indeed not yet properly upgraded to 1.2.0. Having done that there were no further issues in joining the server.
