### ISSUE TITLE
Perspective key not rebindable to key 'g'

### ISSUE THREAD

**Issue by GeefireMC** [TeamAOF/All-of-Fabric-6#52]
When I attempt to rebind the 'Toggle Perspective' key (F5) to the 'g' key, it doesn't work despite there being no conflicts in the keybinds menu.

![](https://i.imgur.com/AqOragt.png)

**Comment by hterez** [comment]
Also does not work with Travelers Backpack keybinds, again despite showing no conflicts

**Comment by parmigggiana** [comment]
I just tested it and both of these problems are solved for me by replacing Controlling with amecs (#79)

**Comment by hokomili** [comment]
I've found the specific mod that use this key.
https://github.com/lilypuree/Decorative-Blocks/issues/82
