### ISSUE TITLE
Luggage Causes Multiple Issues

### ISSUE THREAD

**Issue by jyapc** [TeamAOF/All-of-Fabric-6#57]
Take serious caution when using the luggage mod, he ranges from a mild nuisance to nuclear bomb

There are a few issues the luggage mod creates with this modpack, a few that me and my friends have found while playing on our server. The first issue we found is that if a player is using luggage they will occasionally lose the ability to attack vanilla mobs. We isolated the issue to Luggage, so something there has to be the case. We were able to fix this issue by just leaving the world, and then closing the minecraft application. Reopening it fixes the problem.

The next issue is that putting luggage vinery shelves causes those chunks to be chunkbanned. Any player that loads the chunk with luggage on a vinery shelf will be kicked from the server. We are still resolving this issue because the owner of the server (not me) never backed it up (our fault I know).

**Comment by Linguardium** [comment]
can you post the vinery+luggage crashlog? it should be easy to resolve with that

**Comment by jyapc** [comment]
We fixed the issue by just temporarily uninstalling luggage and destroying what it was placed in, solved the issue no problem
