### ISSUE TITLE
Keybinds won't allow for extra keys

### ISSUE THREAD

**Issue by Wahad** [TeamAOF/All-of-Fabric-6#63]
I am playing on a server with AOF6 1.2.0 and can't seem to bind any keys using a combination of SHIFT or CTRL plus another key (i.e. SHIFT+E, or CTRL+T)

When attempting to do so, it just locks in the CTRL or SHIFT key as the keybind. I know this should be possible, as there are already preset keybinds that use a combination, and I've used it plenty of times in other modpacks.

Is this a known issue or am I just doing it wrong?

**Comment by Linguardium** [comment]
generally this feature is added by a mod. there are several mods that can add this feature (such as amecs) but they are not in the pack

**Comment by Wahad** [comment]
Is there a possibility for such a mod to be added to the pack? I'm not sure if they are available for Fabric, but it would make using all the things so much more user friendly.

**Comment by WraithStar** [comment]
@Wahad Technically you could do the swap I've suggested in #79 in your local installation even right now.
Just delete `Controlling-fabric-1.19.2-10.0+7.jar` from your mod directory and add AMECS Fabric (link is in the referenced issue).

I can't really tell if this would work on multiplayer (not sure if the server admin has to change the mods too), but on singleplayer this should give you no problems at all.
