### ISSUE TITLE
Craft conflict: Flute can't be crafted [1.3.0]

### ISSUE THREAD

**Issue by AlanNoGithub** [TeamAOF/All-of-Fabric-6#69]
Trying to craft the flute with REI:
![image](https://user-images.githubusercontent.com/67552273/212595451-d4306100-e0ea-489b-acd7-ce454a91a045.png)

in place of the flute appears the bamboo shutter:
![image](https://user-images.githubusercontent.com/67552273/212595458-31515ce1-6f12-4c04-b92f-c698f34aa399.png)

**Comment by ImAK9** [comment]
Fixed in 1.4.0
