### ISSUE TITLE
Recipe Conflict: Grapevine Stem conflicts with Oak Beams

### ISSUE THREAD

**Issue by fridayd** [TeamAOF/All-of-Fabric-6#73]
As of 1.3.0, Oak Beams are uncraftable.

**Comment by WraithStar** [comment]
Seems to be a conflict with the recipe of the grapevine stem

![immagine](https://user-images.githubusercontent.com/33436040/213186008-1a1eb85b-19fa-42c1-947c-f8ef82e55bf2.png)

**Comment by ImAK9** [comment]
Fixed in 1.4.0
