### ISSUE TITLE
[Suggestion] Enchanting Infuser

### ISSUE THREAD

**Issue by WraithStar** [TeamAOF/All-of-Fabric-6#80]
Welp, to be honest, more than an actual suggestion this is just a personal rant towards the RNGesus, who really doesn't want to give me that Fortune III enchantment...(i know you can craft it for the mining tool, but that one doesn't work for mining budding crystal shards)

Won't mind if...well...unlucky people like me won't have the cake, but I'll just deal with it I guess...

Tested this version on AOF6 v1.3, no issues so far: https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-forge/files/4041212. 

It requires also Puzzles Lib: https://www.curseforge.com/minecraft/mc-mods/puzzles-lib/files/4041205

**Comment by dandin87** [comment]
There is already a block from bumblezone that allows picking enchantments. Spectrum also has ways of crafting the enchantment book you want and leveling tht enchant up.
