### ISSUE TITLE
[Suggestion] Wired Redstone (Bundled cables)

### ISSUE THREAD

**Issue by Vincent-HD** [TeamAOF/All-of-Fabric-6#81]
Hi,
I think this mod would be a cool thing to have, I was tinkering with some Computer Craft, and I needed to have more outputs and inputs with a project with Create, and I was limited to computer's sides to be able to get/set redstone signals. So getting bundled cables like in old days of Computer Craft would be very cool.

Overall I think this would make Computer Craft way more valuable, the mods seems stable, and the developer seems very active on the development side

**Comment by MynockSpit** [comment]
Curseforge link for context: https://www.curseforge.com/minecraft/mc-mods/wired-redstone

**Comment by MynockSpit** [comment]
I don't have the power to re-open this, but wired-redstone (or a similar mod) has not been added. Should be re-opened.
