### ISSUE TITLE
Unhurtable Mobs

### ISSUE THREAD

**Issue by jyapc** [TeamAOF/All-of-Fabric-6#83]
A new issue has cropped up in our server. There are some mobs that will spawn around players, these mobs cannot be hit, typically they are not vanilla mobs. Typically the mobs have been the mobs for The Graveyard and Probably Chests Mimics. 

The probably chests mimics will spawn around an individual player frequently and are unkillable. Say if 4 people are online only 1 will have the mimics spawn around them.

The Graveyard enemies are less frequent, and don't spawn around an individual player. But otherwise the same problem, nobody is able to hurt them.

We have been trying to troubleshoot for the last few days to try and find the source of this issue, thinking maybe a mod we've interacted with is causing it like the Luggage issue I found before. But we haven't found anything as of yet.

**Comment by WraithStar** [comment]
I had a mob that caused the whole server to crash in 1.2.0. Worked around by having someone else (who was far away from the bugged mob) connect to the server and wait few minutes.

Unsure if it's related, though.

**Comment by jyapc** [comment]
It's been going on since 1.2 but we're on 1.3
