### ISSUE TITLE
[Suggestion] [Recipe] Block of Amethyst Dust should craft into hexcasting Amethyst Dust instead of tech reborn Amethyst Dust.

### ISSUE THREAD

**Issue by Churn3d** [TeamAOF/All-of-Fabric-6#86]
Opened a Magic Epic Lootbag and got a Block of Amethyst Dust. It uncrafts into the wrong dust and won't work in hex casting spells.

**Comment by jan-akesi** [comment]
it's been a while 
please fix this

**Comment by ImAK9** [comment]
I’ll have this fixed by next update.
