### ISSUE TITLE
Can't place Salt from Bewitchment because it don't exist.

### ISSUE THREAD

**Issue by Kaygin8021** [TeamAOF/All-of-Fabric-6#87]
Having a lot of issues with Bewitchment due to the fact I can't place down salt so I can keep mobs in a salt like cage.

**Comment by Linguardium** [comment]
the Bewitchment quest tells you to combine 2 salt to get bewitchment salt. bewitchment salt can be placed.

**Comment by Kaygin8021** [comment]
thank you very much.
