### ISSUE TITLE
Instant crash to Desktop when attempting to cast hex spell with staff. 0.1.2

### ISSUE THREAD

**Issue by Clonephaze** [TeamAOF/All-of-Fabric-6#9]
When attempting to cast a hex using a staff from the Hexcasting mod, my game freezes for a second, says it's saving the world, then the whole instance crashes. I was able to reproduce it 3 times in a row, with and without shaders enabled. No extra mods added or taken out, no odd settings afaik. 
[crash-2022-11-20_23.16.06-client.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/10055442/crash-2022-11-20_23.16.06-client.txt) With shaders
[crash-2022-11-20_23.29.37-client.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/10055496/crash-2022-11-20_23.29.37-client.txt) Without shaders

**Comment by ImAK9** [comment]
Reported it to their issue tracker here: https://github.com/gamma-delta/HexMod/issues/313
