### ISSUE TITLE
Server crashed and I cannot join anymore to my world

### ISSUE THREAD

**Issue by FightMan01** [TeamAOF/All-of-Fabric-6#90]
We was playing and we had powah generators with tech reborn and powah cables. When I placed down an Applied Energistics Energy Acceptor the server crashed and since the if we connect and load the chunks the server crashes immediately. 
Here is the latest log: https://pastebin.com/iee04aqp

**Comment by Linguardium** [comment]
known TR issue, unfortunately. you will need to edit the world nbt to remove the negative value being pushed https://github.com/TechReborn/TechReborn/issues/3085

**Comment by ImAK9** [comment]
This is a mod issue and nothing we are able to fix sadly.

**Comment by Frontrider** [comment]
This bug got a possible fix in powah.
https://github.com/Technici4n/Powah/releases/tag/v4.0.10
