### ISSUE TITLE
Server crashed when joining my dedicated server of aof6

### ISSUE THREAD

**Issue by anerrorpage** [TeamAOF/All-of-Fabric-6#91]
when i join it kicked me and the command prompt on server crashed. here's my latest crash log

[crash-2023-02-08_00.00.45-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/10680729/crash-2023-02-08_00.00.45-server.txt)

**Comment by Linguardium** [comment]
You left a farm running until too many items spilled into the world, now the world takes too long to process those item entities and crashes. remove the entities from the world or remove the region file from the entities folder in the world save to remove ALL entities from that region. (1 region is 16x16 chunks, 1 chunk is 16x16 blocks)

**Comment by 800020h** [comment]
a region is 32x32 chunks

**Comment by anerrorpage** [comment]
Thanks to @Linguardium for helping, my server is back again!
