### ISSUE TITLE
Botania Crashes game.

### ISSUE THREAD

**Issue by MrLoLf** [TeamAOF/All-of-Fabric-6#92]
I am using the latest version of Aof6 on Curse Forge. My logs can be seen here
[latest.log](https://github.com/TeamAOF/All-of-Fabric-6/files/10688247/latest.log) 
and the 
[crash-2023-02-08_18.16.09-client.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/10688252/crash-2023-02-08_18.16.09-client.txt)
 there. There is a new Botania Version available that might fix this issue, but I haven't tested it. And won't test it, as I don't have time for it.
I hope to see an update soon, that might fix some of that errors, of the log.

**Comment by Linguardium** [comment]
a fabric api update will resolve this
