### ISSUE TITLE
Manganese Dust (Stainless Steel and Titanium), Fluid Conflicts, and Misc.

### ISSUE THREAD

**Issue by Nitrogen8809** [TeamAOF/All-of-Fabric-6#97]
I've been playing this modpack for an unhealthy amount of time and have learned multiple things. I'm not sure if anyone else has brought these up, but I feel like I really need to.

Manganese Dust can _only_ be obtained by getting Red Garnet and:
1. Macerating it to get Red Garnet Dust.
2. Throwing the Red Garnet Dust in an Industrial Centrifuge to get Spessartine Dust.
3. Throwing the Spessartine Dust in to an Industrial Electrolyzer.
4. Obtain Manganese.
**_Then_**, you can use the Manganese to create Stainless Steel.
However, you need a lot of Stainless Steel to progress in Modern Industrialization. That, and there are no means to create Stainless Steel exclusively in the confines of the Modern Industrialization Mod - it must be done with Tech Reborn.
So it became clear to me that something was wrong. I realized that when you place Raw Iron in a Centrifuge, it creates Iron Dust and Crushed Manganese Powder. However, you can't turn the Crushed Manganese Powder into regular Manganese Powder. (Like how you can do this maceration process with Mozanite Ore>Crushed Mozanite Dust>Mozanite Dust.)
It became clear to me that the current process of creating Stainless Steel is absurdly inefficient and tedious - and that there's very likely a better method that is inaccessible. I know this because even if you obtain 100k Ruby Ore from the Mining Drills in Industrial Revolution, use Fortune III to get as much Red Garnet as possible, and use all of it to make Manganese - it's _still_ not enough Manganese to create all of the Stainless Steel you'll need.

I can totally understand that since Tech Reborn and Modern Industrialization have a lot of similar items and fluids, they're probably a pain to fix up - but please fix Manganese. You need a _lot_ of Stainless Steel to progress in Modern Industrialization.
With that out of the way, there are a few other things I wanted to mention.

1. Having multiple of the same fluid, such as Tech Reborn's Sulfuric Acid and Modern Industrialization's Sulfuric Acid, makes it difficult to keep track of and somewhat inconvenient if you're using Applied Energistics 2 to store two of the exact same fluid - in a fluid cell that only offers 5 types of fluid. This problem is kind of in the same vein of how you can't use a similar fluid in another mod.

2. There's a book for Applied Energistics 2 that explains many of the devices in the mod - but there's no way to obtain it without using cheats.

3. The Crystal Apothecary from Spectrum doesn't work on Flawless Budding Certus Quartz block from Applied Energistics 2. (Not sure if this is intended or not, but it would be incredibly convenient since you need a lot of it.)

4. The servos from Industrial Revolution seem to visually just disappear overtime when on a pipe. Also, they never neatly stack back into your inventory and seem to always take up another spot (regardless of if a filter was applied to them.) (This is also likely a fault of the mod itself, but I don't know.)

**Comment by Linguardium** [comment]
have you checked the quest path to stainless? you should have an oil mining setup processing.  raw iron->centrifuge->crushed manganese dust in chemical reactor with sulfuric acid, etc

you already should have mining setups so adding a step to the raw iron processing as soon as you can should be a non-issue

**Comment by Nitrogen8809** [comment]
I see, I'll have to check later today.
Maybe I really just never noticed there was an alternate recipe.

**Comment by Bellabong** [comment]
It's not really "alternate, since it's the standard MI recipe path. When dealing with MI materials, try and deal with only MI machines. Adding TR to the mix is going to add confusion and slow things down drastically (by the very nature of TR simply being slower)

**Comment by Nitrogen8809** [comment]
I see. I just grossly misinterpreted the method for creating Manganese Dust in large quantities. It's much simpler than I thought - but I have a goo-goo ga-ga caveman brain. I was indeed using an inefficient method instead of the typical method, because I didn't consider how rapidly that Manganese Tiny Dust would add up.

I think the reason I came to that conclusion was because some higher level materials like Titanium are easier to make using the Tech Reborn equipment - so I assumed there was some conflicting method that was lost. I dunno.

As an apology for my stupidity, I do have another actual potential bug.
The Slaughter Machine from Industrial Revolution doesn't accept certain tools. In my case, the Bedrock Sword from Spectrum. There are likely other tools it doesn't accept. I guess I'll just make a new thread in case I come across more issues.

**Comment by Linguardium** [comment]
Bedrock tools breaking in indrev machines is a known issue and has been reported already
